### ISSUE TITLE
Resource monitor error

### ISSUE THREAD

**Issue by ms32035** [chanzuckerberg/terraform-provider-snowflake#109]
A resource monitor is correctly created, but then on a subsequent execution of plan `credit_quota` causes an error
```
Error: sql: Scan error on column index 1, name "credit_quota": converting driver.Value type string ("50.00") to a int64: invalid syntax
```

Snowflake UI presents the quota as `50.00`

**Comment by chauvm** [comment]
This should be fixed in https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/111
