### ISSUE TITLE
schema cannot be imported

### ISSUE THREAD

**Issue by marcinef** [chanzuckerberg/terraform-provider-snowflake#113]
I can create a new schema if one does not exist but I cannot seem to import already existing schema. I tried two formats:

snowflake_schema.schema TEST_SCHEMA
snowflake_schema.schema DB_NAME.TEST_SCHEMA

both are failing. 

$ terragrunt import snowflake_schema.schema TEST_SCHEMA
snowflake_schema.schema: Importing from ID "TEST_SCHEMA"...
snowflake_schema.schema: Import prepared!
  Prepared snowflake_schema for import
snowflake_schema.schema: Refreshing state... [id=TEST_SCHEMA]

Error: 2 fields allowed

Any suggestions?

**Comment by edulop91** [comment]
Looks like the schema IDs are saved as <database>|<schema>. (here)[https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/master/pkg/resources/schema.go#L67]

maybe try somethingl like terragrunt import snowflake_schema.schema "<database_name>|TEST_SCHEMA"

**Comment by marcinef** [comment]
Yup, it worked. Thanks! 
terragrunt import snowflake_schema.schema 'db_name|schema_name'

**Comment by davehowell** [comment]
I think there's a general issue. What is the import syntax?  It would be helpful to add some note about that to the docs.

I experienced the same thing trying to import a `snowflake_stage` resource, it was expecting 3 fields. 
This issue helped me get it working. I used this:

` terraform import snowflake_stage.test_stage "<database_name>|<schema_name>|<stage_name>"`
