### ISSUE TITLE
Feature request: Provisioning of PIPE (Snowpipe) object

### ISSUE THREAD

**Issue by doctoryes** [chanzuckerberg/terraform-provider-snowflake#115]
The functionality to add a Snowpipe as the `CREATE PIPE` SQL performs is currently missing from this provider. It'd be nice to be able to manage Snowpipes via Terraform. Details:

https://docs.snowflake.net/manuals/sql-reference/sql/create-pipe.html
https://docs.snowflake.net/manuals/user-guide/data-load-snowpipe.html

**Comment by marcinef** [comment]
https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/128

**Comment by pwnage101** [comment]
Looks like the PR merged and released in v0.10.0.
