### ISSUE TITLE
Feature request: Provisioning of a STAGE Snowflake object

### ISSUE THREAD

**Issue by doctoryes** [chanzuckerberg/terraform-provider-snowflake#117]
The functionality to add a Snowpipe as the `CREATE STAGE` SQL performs is currently missing from this provider. It'd be nice to be able to manage these objects via Terraform. This functionality would undoubtedly be more difficult than other objects, due to the platform abstraction leaking and the need to specify platform-specific parameters.

https://docs.snowflake.net/manuals/sql-reference/sql/create-stage.html

**Comment by ryanking** [comment]
Fixed in #121
