### ISSUE TITLE
Add storage_integration

### ISSUE THREAD

**Issue by LouisAmon** [chanzuckerberg/terraform-provider-snowflake#125]
Storage Integrations consist in linking Snowflake accounts with AWS, Azure or GCP accounts via Roles.

It's currently the best practice for connecting with your cloud environment, and it definitely one of the main benefits from being on Terraform : you can create the AWS Role (for example) and pass it as parameter to the Snowflake StorageIntegration 👍 

https://docs.snowflake.net/manuals/sql-reference/sql/create-storage-integration.html

I think a first step would be AWS, then Azure and GCP (GCP was in preview until recently)

**Comment by sjauld** [comment]
I'll have a bash at this now.
