### ISSUE TITLE
Apostrophe character in comment breaks schema resource creation

### ISSUE THREAD

**Issue by pwnage101** [chanzuckerberg/terraform-provider-snowflake#127]
If the `comment` parameter on a snowflake_schema resource contains an apostrophe, that's probably not escaped correctly during resource creation because it causes snowflake syntax errors and fails the creation.

I haven't tested other resources, but I suspect it might be also problematic elsewhere.

I'd paste the error I got, but it's a syntax error on the *next* token following the apostrophe, which isn't going to be consistent for this bug.

**Comment by ryanking** [comment]
@pwnage101 I am not surprised by this, we have not been diligent about escaping.
