### ISSUE TITLE
Error when you create an internal stage

### ISSUE THREAD

**Issue by thalesmello** [chanzuckerberg/terraform-provider-snowflake#129]
If you try to create an internal stage like:

```
resource snowflake_stage my_stage {
  name     = "MY_STAGE"
  database = "TEST"
  schema   = "PUBLIC"
}
```

When you do a `terraform apply`, you get `Error: sql: Scan error on column index 9, name "region": converting NULL to string is unsupported`

This apparently is because [`region` cannot be `nil`](https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/df3a407eb2436f1c957d8b4b269248fbb29c0f09/pkg/resources/stage.go#L430). I'm not sure what could be done to solve this problem.

**Comment by thalesmello** [comment]
I have a pull request open at #130

**Comment by ryanking** [comment]
@thalesmello we can consider this fixed, yeah?

**Comment by thalesmello** [comment]
Correct. Closing the issue
