### ISSUE TITLE
Resource Monitor CREDIT_QUOTA type

### ISSUE THREAD

**Issue by dehume** [chanzuckerberg/terraform-provider-snowflake#145]
I saw issue https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/109 about converting the credit quota from an int to a float in resource monitors but when I try and create a  monitor I'm getting a data type error.

```
Error: error creating resource monitor EXAMPLE_MONITOR: 001008 (22023): SQL compilation error:
invalid value [5.00] for parameter 'CREDIT_QUOTA'
```

Using the generated SQL but using `5` instead of `5.00` creates the object successfully.

**Comment by Aaron-K-T-Berry** [comment]
Can confirm this is still an issue. Currently you are unable to create a resource monitor with credit quota other than 0 with all other values resulting in the above error. #111 seems suspect as the cause of this issue.

**Comment by NJAldwin** [comment]
We have run into this as well.

**Comment by NJAldwin** [comment]
We are also running into this.

If I'm understanding the original issue #109 correctly, even though this parameter is an int, it is returned from Snowflake as a float?  Seems likely that the fix for both issues would be to use an int for the parameter, but to accept a float from the UI?

**Comment by Aaron-K-T-Berry** [comment]
For anyone looking for a workaround to this problem in the mean time you can use a snowsql run via Terraform to update the credit quota after provisioning the resource monitor. Examples below.

```
locals {
  resource_monitor_name = "FOO_RESOURCE_MONITOR"
  credit_quote          = 100
  warehouse_name        = "FOO_WAREHOUSE"
}

resource "snowflake_resource_monitor" "resource_monitors" {
  lifecycle {
    ignore_changes = [
      # Ignore changes to credit quota as they are modified via a manual sql file
      credit_quota
    ]
  }

  name         = local.resource_monitor_name
  credit_quota = 0
}

resource "null_resource" "resource_monitor_credit_quotas" {
  depends_on = [snowflake_resource_monitor.resource_monitors]

  # Run the script every time apply is run
  triggers = {
    run_always = "${timestamp()}"
  }

  provisioner "local-exec" {
    command = "/usr/local/bin/snowsql -o variable_substitution=true  -f ${path.module}/update-quotas.sql --variable resource_monitor=${snowflake_resource_monitor.resource_monitors.name} --variable credit_quota=${local.credit_quote}"
  }
}

resource "snowflake_warehouse" "warehouses" {
  name             = local.warehouse_name
  resource_monitor = snowflake_resource_monitor.resource_monitors.name
}
```

And the `update-quotas.sql` looking something like.
```SQL
ALTER RESOURCE MONITOR &resource_monitor SET CREDIT_QUOTA=&credit_quota;
```
