### ISSUE TITLE
database_grant: ALL privilege will always create resource

### ISSUE THREAD

**Issue by asavoy** [chanzuckerberg/terraform-provider-snowflake#148]
When using `snowflake_database_grant` with `privilege = ALL`, the Terraform plan will keep asking to recreate the resource.

I'm guessing this is because, as noted in another issue, ALL is an alias in Snowflake.

## Steps to reproduce

The code:

```terraform
resource "snowflake_database" "test_database" {
  name    = "TEST_DATABASE"
  comment = ""
}

resource "snowflake_role" "all_role" {
  name     = "ALL_ROLE"
}

resource "snowflake_database_grant" "all" {
  database_name = "${snowflake_database.test_database.name}"
  privilege = "ALL"
  roles = ["${snowflake_role.all_role.name}"]
}
```

Then `terraform apply` it once to apply the change.

Then run `terraform apply` again and see the same pending change:

```
Terraform will perform the following actions:

-/+ snowflake_database_grant.all (new resource required)
      id:               "TEST_DATABASE|||ALL" => <computed> (forces new resource)
      database_name:    "TEST_DATABASE" => "TEST_DATABASE"
      privilege:        "ALL" => "ALL"
      roles.#:          "0" => "1" (forces new resource)
      roles.3951068007: "" => "ALL_ROLE" (forces new resource)
```

**Comment by davehowell** [comment]
I thought perhaps a workaround to this would be to write multiple privileges in the string.

For example it is valid to run this SQL:
`GRANT USAGE, CREATE SCHEMA ON DATABASE "TEST_DATABASE" TO ROLE "ALL_ROLE";` 

I tried this out and it fails because there is validation requiring there to be only one privilege specified.

e.g.
```terraform
resource "snowflake_database_grant" "all" {
  database_name = "${snowflake_database.test_database.name}"
  privilege = "USAGE, CREATE SCHEMA"
  roles = ["${snowflake_role.all_role.name}"]
}
```

Got this error
```
Error: snowflake_database_grant.all: expected privilege to be one of [ALL CREATE SCHEMA IMPORTED PRIVILEGES MODIFY MONITOR OWNERSHIP REFERENCE_USAGE USAGE], got USAGE, CREATE SCHEMA
```

I tried a few variations, none of these work:
```
privilege = "USAGE CREATE SCHEMA"
privilege = "USAGE|CREATE SCHEMA"
privilege = ["USAGE", "CREATE SCHEMA"]
```
Of course the list doesn't work, the property is a string.

The README says:

> Across the entire Snowflake account, all of the databases to which a single grant is attached must be declared by a single snowflake_database_grant resource.

How is it possible to specify multiple databases in a single `snowflake_database_grant` resource? The `database_name` property is also a string.

**Comment by PatrickMcAfee-Eagle** [comment]
I believe I'm also seeing this exact same issue with snowflake_schema_grant and the "ownership" privilege.

`  # module.application_environment.module.snowflake.module.dataquality_db.snowflake_schema_grant.ownership must be replaced
-/+ resource "snowflake_schema_grant" "ownership" {
        database_name = "MY_DATABASE"
      ~ id            = "MY_DATABASE|PUBLIC||OWNERSHIP" -> (known after apply)
        privilege     = "OWNERSHIP"
      ~ roles         = [ # forces replacement
          + "MY_USER",
        ]
        schema_name   = "PUBLIC"
      - shares        = [] -> null
    }`

**Comment by alex-96-eng** [comment]
+1

**Comment by ryanking** [comment]
Going to close this as we are going to be [removing support for ALL grants](https://github.com/chanzuckerberg/terraform-provider-snowflake/discussions/318).

If still occurring after that, feel free to re-open.
