### ISSUE TITLE
Streams and Tasks support

### ISSUE THREAD

**Issue by stephenoneal** [chanzuckerberg/terraform-provider-snowflake#157]
would like to see Snowflake Streams https://docs.snowflake.com/en/user-guide/streams.html  and Tasks https://docs.snowflake.com/en/user-guide/tasks-intro.html support so those types of objects can be pulled into the terraform files.

**Comment by ryanking** [comment]
@stephenoneal That's a good idea and would be a great contribution to this project.

My team (and other contributors) are mostly building things they need for their own work. I am happy to help get PRs reviewed, though we are a bit slow right now given the shelter-in-place order in the bay area's disruption to our work.

**Comment by sfc-gh-afedorov** [comment]
Looks like this may be done?

https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/main/pkg/resources/stream.go
https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/main/docs/resources/stream.md
https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/main/pkg/resources/task.go
https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/main/docs/resources/task.md
