### ISSUE TITLE
Pre-release tag for v10+ for next version of provider

### ISSUE THREAD

**Issue by Aaron-K-T-Berry** [chanzuckerberg/terraform-provider-snowflake#162]
It would be great to get a pre release tag for the next version of the provider so that the new resources can be tested out. 

Even better would be having the latest commit to master tagged as an edge release so the latest commit to master is always available for download as a tagged release,

**Comment by ryanking** [comment]
I went ahead and released 0.11.0. If there are any problems let us know.
