### ISSUE TITLE
schema creation sql error

### ISSUE THREAD

**Issue by jessdaubner** [chanzuckerberg/terraform-provider-snowflake#166]
```
Error: sql: Scan error on column index 8, name "retention_time": converting driver.Value type string ("") to a int64: invalid syntax
```

Similar error message to that encountered in [Issue #109](https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/109). 

It's not entirely clear if this error is being thrown after the creation of schemas. `data_retention_days `  was not specified when the schemas were initially created. In the Snowflake UI, a `data_retention_time_in_days` of 0 appears to be a null value.

**Comment by Aaron-K-T-Berry** [comment]
Seems related to #145 as well

**Comment by ryanking** [comment]
@jessdaubner can you share the configuration that causes this error?

**Comment by ryanking** [comment]
I think this was fixed with our changes to the way we scan sql results. If not, feel free to re-open.
