### ISSUE TITLE
Can't create a file format TOK_CONSTANT_LIST does not exist

### ISSUE THREAD

**Issue by Mokubyow** [chanzuckerberg/terraform-provider-snowflake#168]
Has anyone else got the had trouble creating a snowflake stage with this provider? I keep getting the following error:

```
Error: error creating stage TABLE_RAW: 002003 (02000): SQL compilation error:
File format 'TOK_CONSTANT_LIST' does not exist or not authorized.
```

I know for a fact that the file format does indeed exist because I was able to create the stage manually in a snowflake worksheet. The only caveat being that I had to provide the fully qualified file_format:

```
create or replace stage prod.public.table_raw
url = 's3://<bucket>/prod/'
file_format = "PROD.PUBLIC.RAW"
storage_integration = "RAW_DATA"
```

Here is my stage resource:

```
resource "snowflake_stage" "table_raw" {
  name                  = "TABLE_RAW"
  database            = "PROD"
  schema              = "PUBLIC"
  file_format         = "RAW"
  url                       = "s3://<bucket>/prod/"
  storage_integration = "RAW_DATA"
}
```

When I try adding `{DB}.{SCHEMA}.{TABLE}` to the file_format in terraform I get the following error:

```
Error: error creating stage TABLE_RAW: 001003 (42000): SQL compilation error:
syntax error line 1 at position 202 unexpected '.'.
syntax error line 1 at position 202 unexpected '.'.
syntax error line 1 at position 220 unexpected ')'.
```

**Comment by brewkode** [comment]
I see the same issue as well. The actual SQL that seems to be executed on Snowflake's side is to the effect 
`ALTER STAGE %v SET FILE_FORMAT = (%v)`. In comparison, when I run the following version of SQL directly on my Snowflake console it works.

Working version:
`ALTER STAGE %v SET FILE_FORMAT = %v` **(Without braces around value)**

**Comment by Mokubyow** [comment]
@brewkode That is correct! The only thing I will mention is that `RAW` is a file_format so it would be:

```
resource "snowflake_stage" "table_raw" {
  name                  = "TABLE_RAW"
  database            = "PROD"
  schema              = "PUBLIC"
  file_format         = "FORMAT_NAME = RAW"
  url                       = "s3://<bucket>/prod/"
  storage_integration = "RAW_DATA"
}
```

**Comment by alok08** [comment]
Hello @kyle-hamlin ,

Below code is working in my system:

resource "snowflake_stage" "table_raw" {
  name                  = "TABLE_RAW"
  database            = "PROD"
  schema              = "PUBLIC"
  file_format         = "**FORMAT_NAME = DB_NAME.SCHEMA_NAME.**RAW"
  url                       = "s3://<bucket>/prod/"
  storage_integration = "RAW_DATA"
}

Note: I highlighted my change.

Thanks
