### ISSUE TITLE
Feature Request: declare a role to assume when provisioning resources.

### ISSUE THREAD

**Issue by Aaron-K-T-Berry** [chanzuckerberg/terraform-provider-snowflake#169]
Due to the behaviour that the role that creates a snowflake resource gets automatic ownership of that resource it would be helpful to be able declare what role that should provision / destroy a snowflake resource.

**Comment by sjauld** [comment]
How are you creating resources *without* using a role?

```
# The ACCOUNTADMIN role
provider "snowflake" {
  alias = "aa"

  username = var.sf_username
  account  = var.sf_account
  region   = var.sf_region
  role     = "ACCOUNTADMIN"
}

# The SYSADMIN ROLE
provider "snowflake" {
  alias = "sa"

  username = var.sf_username
  account  = var.sf_account
  region   = var.sf_region
  role     = "SYSADMIN"
}
```

**Comment by Aaron-K-T-Berry** [comment]
@sjauld This is one method to achieve it but it would be nice to assume one role for the whole provider and then assume more specific roles for some resources. In SQL it would be equivalent to using the `USE ROLE` statement before creating a resource.

**Comment by sjauld** [comment]
Using statements like `USE ROLE` is a bad idea since you are impacting other resources due to the shared client in the provider. Hence using different providers if you want different roles is a highly sensible way of achieving this, plus it's already available.

**Comment by Aaron-K-T-Berry** [comment]
I didn't think about using 2 different providers but I do like the use of the provider in that pattern. One advantage i do see assuming a role at the resource level could provide is the ability for variables and resource outputs to be used to drive the ownership of other deployed resources in snowflake. 

I haven't had a big dive into the code base to i wasn't aware that could be a potential issue with the shared client.  I understand this feature would probably be quite a large undertaking so closing this issue. 😄

**Comment by sjauld** [comment]
Yeah there are definitely some benefits of being able to specify a role outside of the provider block - for example you can't terraform a role and then use that role to create more resources, since the connection is instantiated before the role is created. I'm just not sure how to work around the fact that all resources need to be created in a single SQL statement.
