### ISSUE TITLE
"sql: no rows in result set" error

### ISSUE THREAD

**Issue by pwnage101** [chanzuckerberg/terraform-provider-snowflake#188]
We occasionally encounter this error when trying to run `plan`/`refresh` after a failed `apply` (e.g. can happen if the computer running `apply` gets terminated or if snowflake throws an error in the middle of an apply, like if we're trying to make terraform create an object that already exists...there are many reasons why an `apply` will error out without cleaning itself up): 

```
$ terraform refresh
... (a bunch of "Refreshing state..." lines)

Error: sql: no rows in result set
```

We typically remedy the issue by deleting grants from the state that don't exist in Snowflake, but it can be extremely difficult to manually find those instances since our terraform state has thousands of resources.

I think there's some grant-related code in the provider that is running a SQL query to get a list of grants and just blindly expecting the result to be non-empty.  I think the provider needs to handle this more elegantly, because I would hope that terraform `refresh` should be more robust since it is a prerequisite to running terraform `plan` and `apply`.

**Aside:** It is no surprise that the state is corrupt, since we ARE talking about the `apply` unexpectedly exiting or getting terminated.  So I agree that there are other provider bugs and issues with our infrastructure which must first exist and have happened before we encounter this bug, but I would rather treat those as separate bugs.  Since this happens to us so often and it's always the same error, I feel like fixing this is the low-hanging fruit.

**Comment by swathiJayav** [comment]
We are also  experiencing this bug.

**Comment by ryanking** [comment]
I think what we need to do is set the id of unfound resources to "", which will effectively remove them from the state for you.

I don't have a good way to test this though. @pwnage101 do you have a reproducible failure here?

**Comment by ryanking** [comment]
Leaving more note here in case someone wants to pick this work up - it seems that in our read paths we need to figure out errors that mean "resource doesn't exist" and in those cases call `d.SetId("")` to remove the resource from the state. Given the way our code for reading grants is written, this might take a fair bit of refactoring to achieve. Doing it in pieces would be fine.

[Example](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_iam_access_key.go#L131) of what I am talking about from the aws provider (reading that provider is how I figure out how to do things in providers.

**Comment by luis02lopez** [comment]
Happening here with a terraform import
