### ISSUE TITLE
feat: Ability to specify auth as variables to provider

### ISSUE THREAD

**Issue by mhaley-miovision** [chanzuckerberg/terraform-provider-snowflake#190]
There are many good reason to support providing authentication details to the provider via environment variables, but there are also many good reason to support accepting authentication details in the configuration of the provider itself.  For instance, my team uses additional tooling like terragrunt, and a common pattern that is able to securely fetch and provide, as TF variables, credentials for any provider that we use.

Currently we would be unable to use this provider because it only accepts credentials via environment variables.  We should extend the functionality of the provider to accept variables both as environment variables, and also as configuration within the terraform script itself.

**Comment by ryanking** [comment]
@mhaley-miovision Have you tried using it the way you want to? If so what error message did you get?

We use only environment variables, but AFAICT it should work without them.

**Comment by mhaley-miovision** [comment]
@ryanking I did not even try or check the source code, I just read the documentation.  Looking at the source, it seems it does support what I am talking about.  That said, there appears to be a gap in the documentation (unless I am missing something else) about the ability to configure the provider purely from code.

**Comment by ryanking** [comment]
Glad you figured it out. Yes our docs are not 100%. Pull requests welcome. :)
