### ISSUE TITLE
browser auth hangs

### ISSUE THREAD

**Issue by ataki** [chanzuckerberg/terraform-provider-snowflake#199]
hi Ryan + co, thanks for building this! We're looking into investing in this tool for managing a subset of our Snowflake assets.

Our company uses an SSO setup with Snowflake, and I enabled the browser auth flow to test how `terraform import` would work for bringing a single db resource under terraform management. I'm testing this on my local dev environment (Macbook, Catalina 10.15.4). On my browser, I'm able to authenticate with Snowflake, and see the browser redirect back to `http://localhost:63255/?token=...`. However, the `terraform import` command hangs thereafter. Has anyone seen this behavior before? I noticed the code proxies to the `gosnowflake` implementation for `AuthTypeExternalBrowser`, but wondering if anyone here from CZ has successfully tested with this flow or run into this issue.

I have a screencap I can share of the behavior.

I wound up getting around it by creating an admin user/pass. That allowed `terraform import` to run successfully.

**Comment by patangay** [comment]
Hi Jim, at CZI, we do not use the SSO browser auth, we use public/private key pairs instead. I'm afraid the browser auth feature is not well tested.

**Comment by ataki** [comment]
makes sense. we can do some digging and offer a fix if you'd be willing to take a look.

**Comment by patangay** [comment]
@ataki - Yep! That would be great.

**Comment by ataki** [comment]
Did some further digging. I was able to get SSO browser auth working on my local laptop with no changes to the code.

The fix? Keep refreshing the redirect link to `localhost` until it's "registered" by the ExternalAuth handler.

I've verified that this behavior also exists with the external browser auth module provided by the `gosnowflake` module, so it has nothing to do with this repo. Not sure if this is expected behavior from `gosnowflake` but I'll cross-post and ask there.

**Comment by ataki** [comment]
With regards to how you want to handle this ticket: SSO auth is painful to use with this tool. Issuing `terraform plan` opens up a browser tab _for every resource required to sync, every time the command is issued_. When I was testing, I had over 50 tabs open up when I issued a test `terraform plan`. I would have expected only one tab to pop up.

I would suggest possibly removing the section stating support for users or document this less-than-ideal UX. There may be a way to have 1 instead of 50 tabs pop up, but I'm unsure of how hard this would be given the fact that...well...you'd have to circumvent the "Single" part of SSO.
