### ISSUE TITLE
Storage integrations cannot have TYPE altered

### ISSUE THREAD

**Issue by pwnage101** [chanzuckerberg/terraform-provider-snowflake#204]
In code we treat TYPE as an alter-able property:

https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/30ce39a/pkg/resources/storage_integration.go#L239-L242

However, snowflake does not allow TYPE to be altered after creation:

https://docs.snowflake.com/en/sql-reference/sql/alter-storage-integration.html

As a result, our terraform apply failed with the following snowflake error:

```
Error: error updating storage integration: 001420 (22023): SQL compilation error:
invalid property 'TYPE' for 'INTEGRATION - EXTERNAL_STAGE'

  on snowflake_storage_integrations.tf line 10, in resource "snowflake_storage_integration" "s3_storage_integration":
  10: resource "snowflake_storage_integration" "s3_storage_integration" {
```

Also, here was the SQL that got executed, according to the query log:

```sql
ALTER STORAGE INTEGRATION "GCS_STORAGE_INTEGRATION" SET TYPE='EXTERNAL_STAGE'
```

This normally wouldn't be a big problem if it wasn't for the fact that there's another issue which makes terraform always plan to update this value even when there's nothing to change.

**Comment by pwnage101** [comment]
We have confirmed a workaround for this issue. Add the following block to your storage integration:

```
  lifecycle {
    ignore_changes = [type]
  }
```

This somehow prevents HasChange() from returning true, preventing `TYPE` from getting added to the `ALTER STORAGE INTEGRATION` statement.  Keep in mind this does not make it possible to alter type, which still requires the resource to be first destroyed then recreated.

**Comment by ryanking** [comment]
@pwnage101 and @msluyter in these cases did you change the type field in your code?

**Comment by pwnage101** [comment]
In my case, I never specified the type field at all.  When terraform first creates the resource (with no type field specified), the default type is used which i guess is EXTERNAL_STAGE.  But then the next apply seems to want to change it which is the first bug.  The second bug is that it cannot be changed anyway because snowflake just doesn't allow this field (type) to be changed for this resource type (storage integration).

**Comment by ryanking** [comment]
Ok, given that we don't have this resource in our code anywhere, and there are no acceptance tests I don't think I can reasonable fix this right now.

But it seems that we could at least make that field not editable. Given that it can only ever be set to `EXTERNAL_STAGE` this should be fine, right?

**Comment by jnicholsthru** [comment]
I just ran into this again.  yes, setting this to `EXTERNAL_STAGE` would be fine.

**Comment by aidan-melen** [comment]
Ran into the same issue. `lifecycle_ignore` is a confirmed workaround.

**Comment by aidan-melen** [comment]
> Note, I had to quote "type" to get the above to work:
> 
> ```terraform
>  lifecycle {
>     ignore_changes = ["type"]
>   }
> ```

no quotes is for terraform 12 and up I believe
