### ISSUE TITLE
[feature] network policy

### ISSUE THREAD

**Issue by jmak123** [chanzuckerberg/terraform-provider-snowflake#221]
Snowflake allows users to add IP whitelisting to the account. It is managed via command like 
```
create network policy mypolicy2 allowed_ip_list=('192.168.1.0','192.168.1.100');
```
It would be great if this can be terraformed too and it is especially valuable for enterprises that are looking to document/codify their security details.

https://docs.snowflake.com/en/sql-reference/sql/create-network-policy.html

**Comment by ryanking** [comment]
@jmak123 thanks for the interest.

We should support this, but we prioritize things our team uses (and this is not one of them), so I am not sure when we will get to it.

In the meantime, we would be happy to help get a PR merged.

**Comment by grahamplace** [comment]
I'm working on this! PR incoming soon, hoping to have time to put the final touches on it today

**Comment by ryanking** [comment]
Addedin #271.
