### ISSUE TITLE
Docs Missing(?)

### ISSUE THREAD

**Issue by grahamplace** [chanzuckerberg/terraform-provider-snowflake#232]
Thanks for your work supporting this Provider! Very glad we didn't have to write it ourselves 🙂

**Provider Version**

0.13.2

**Terraform Version**

0.12

**Describe the bug**

I can't find the documentation for the resources supported by this Provider

**Expected behavior**

Per the readme: 
> In-depth docs are available [on the Terraform registry.](https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest)

What I see under the [Documentation tab](https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest) on the linked Terraform registry [page](https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest):
![image](https://user-images.githubusercontent.com/19509185/88970881-f9a49a00-d267-11ea-9402-f22d96afb0fe.png)

**Code samples and commands**

NA

**Additional context**

I might be missing something obvious, but if the docs live elsewhere, the readme link to the Terraform registry should probably be updated to avoid confusion.

**Comment by grahamplace** [comment]
Ah I just saw this, almost certainly the cause 
https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/227

**Comment by ryanking** [comment]
Yeah just got that merged, will be there on the next release.

**Comment by ryanking** [comment]
they are up now https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs
