### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by sauln** [chanzuckerberg/terraform-provider-snowflake#235]
**Provider Version**

0.13.2

**Describe the bug**

The readme says that 
> In-depth docs are available on the Terraform registry. 

but the Terraform registry says

> Documentation Unavailable
> This version of the snowflake provider doesn't have any documentation available.

**Expected behavior**

Documentation to be rendered and available somewhere.

**Additional context**

I'm pretty sure just a few days I go I found your documentation rendering on github.

**Comment by ryanking** [comment]
We are working on it. The [PR to enable the docs in the registry](https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/227) went in a few days ago. Working on a release to make them show up today.

**Comment by ryanking** [comment]
they are up now https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs

**Comment by sauln** [comment]
Sweet, thank you!
