### ISSUE TITLE
Error for Azure Asia Pacific Region in Provider Declaration 

### ISSUE THREAD

**Issue by Lachlan-White** [chanzuckerberg/terraform-provider-snowflake#240]
**Provider Version**

0.14.0

**Terraform Version**

0.13.0

**Describe the bug**

Azure Regions seem not to be concatenated properly.
Within the provider definition adding a region of `australia-east` fails

Met with error: 
`Error: error creating database: Post "https://hd12703.australia-east.snowflakecomputing.com:443/session/v1/login-request?requestId=0758b158-9a20-4fc9-841b-1a4097f913a3&request_guid=eb2cc3b3-a521-4f3d-915c-c3664941b279&roleName=ACCOUNTADMIN": x509: certificate is valid for *.us-west-2.snowflakecomputing.com, *.snowflakecomputing.com, *.global.snowflakecomputing.com, *.prod1.us-west-2.aws.snowflakecomputing.com, *.prod2.us-west-2.aws.snowflakecomputing.com, *.us-west-2.aws.snowflakecomputing.com, not _myaccount_.australia-east.snowflakecomputing.com`

**Expected behavior**

Expected the authorisation of the provider to the snowflake APIs

**Additional context**

This problem is correct if the region is input as `australia-east.azure`

**Comment by FlorianFlatau** [comment]
Hi Guys,

i got the same issue for the AZURE region west-europe. I just like to know if this provide is only working with the named US regions and if, when it is planed to implement the EU or other regions?

Thanks a lot!

Florian

**Comment by lachie-white** [comment]
HI all,

Though I would better highlight the workaround to this. Essentially it's just a failure on the Concatenation of strings within the provider block.

So something like the below will work for Azure:

``` HCL
terraform {
  required_providers {
    snowflake = {
      source  = "chanzuckerberg/snowflake"
      version = "0.14.0"
    }
  }
}

provider "snowflake" {
  account  = "account_name"
  region   = "australia-east.azure"
  username = "username"
  password = local.password
  role     = "ACCOUNTADMIN"
}
```

**Comment by ryanking** [comment]
@Lachlan-White sorry for the slow response - I don't really know what is expected here. AFAICT we just pass the region through to gosnowflake to create the DSN.

**Comment by Lachlan-White** [comment]
Hi @ryanking, there is an issue with the translation of the region.

Within my example (and from your documentation) the snowflake provider should accept the input of` `australiaeast `or `australiasoutheast`;

However, to get the snowflake provider to work, you need to pass the region as:
`australia-east.azure`

These fields don't align with the documented regions:
https://docs.snowflake.com/en/user-guide/intro-regions.html#general-regions

**Comment by ryanking** [comment]
Ok I am a bit confused - I don't see where we document this anywhere in this project, so I am not entirely sure what docs of ours you are referring to.

We simply pass the provided region to the [gosnoflake library](https://godoc.org/github.com/snowflakedb/gosnowflake#hdr-Connection_Parameters) and I think we should keep it that way. I will add pointers to the gosnowflake docs.
