### ISSUE TITLE
Question: provisioning account level stuff and databases

### ISSUE THREAD

**Issue by funes79** [chanzuckerberg/terraform-provider-snowflake#243]
Hi,
 in my case for role creation we need to use securityadmin and for database creation we need to use sysadmin. I am not able to deploy in one terraform stack (with sysadmin configured in provider "snowflake") the roles. 

Error: error creating role: 003001 (42501): SQL access control error:
Insufficient privileges to operate on account 'xxxxx';

Is there a way to have multiple artefacts in one single stack, but use different roles to create them? Or should I create a super use what will have all the required permissions?
Thanks for the hint.

**Comment by ryanking** [comment]
Yes you can configure [multiple snowflake providers with aliases](https://www.terraform.io/docs/configuration/providers.html#alias-multiple-provider-configurations) and use them where appropriate. Psuedo-example–

```
provider snowflake {
  alias = "securityadmin"
  role = "SECURITYADMIN"
  ...
}

provider snowflake {
  alias = "sysadmin"
  ...
}

```

**Comment by ryanking** [comment]
@funes79 if that doesn't help, feel free to re-open this issue

**Comment by funes79** [comment]
Thanks! This resolves the issue.
