### ISSUE TITLE
snowflake_pipe resource always planned for recreation even without changes

### ISSUE THREAD

**Issue by sortigoza** [chanzuckerberg/terraform-provider-snowflake#246]
**Provider Version**

The provider version you are using.

0.15.0

**Terraform Version**
v0.11.14

The version of Terraform you were using when the bug was encountered.

**Describe the bug**

the `snowflake_pipe` resources are always (planned to be recreated) recreated even when there are no updates.

```
-/+ snowflake_pipe.raw__violin__public__stage_XXX__pipe (new resource required)
      id:                   "RAW|VIOLIN__PUBLIC|VIOLIN__PUBLIC_STAGE_XXX_PIPE" => <computed> (forces new resource)
      auto_ingest:          "true" => "true"
      comment:              "Owner: Data Team; Terraform: true" => "Owner: Data Team; Terraform: true"
      copy_statement:       "COPY INTO RAW.VIOLIN__PUBLIC.STAGE_XXX FROM '@RAW.VIOLIN__PUBLIC.VIOLIN__PUBLIC_STAGE/XXX/' file_format = (TYPE = 'PARQUET')" => "COPY INTO RAW.VIOLIN__PUBLIC.STAGE_XXX FROM '@RAW.VIOLIN__PUBLIC.VIOLIN__PUBLIC_STAGE/XXX/' file_format = (TYPE = 'PARQUET');" (forces new resource)
      database:             "RAW" => "RAW"
      name:                 "VIOLIN__PUBLIC_STAGE_XXX_PIPE" => "VIOLIN__PUBLIC_STAGE_XXX_PIPE"
      notification_channel: "arn:aws:sqs:us-east-1:XXX:sf-snowpipe-XXX-XXX" => <computed>
      owner:                "SYSADMIN" => <computed>
      schema:               "VIOLIN__PUBLIC" => "VIOLIN__PUBLIC"
```

**Expected behavior**

when there are no updates to the `snowflake_pipe` resources, plan shouldn't have drift.

**Code samples and commands**

Please add code examples and commands that were run to cause the problem.

the terraform resource has the following fields set:

```
resource "snowflake_pipe" "raw__violin__public__stage_XXX__pipe" {
  auto_ingest    = true
  copy_statement = "COPY INTO RAW.VIOLIN__PUBLIC.STAGE_XXX FROM '@RAW.VIOLIN__PUBLIC.${snowflake_stage.raw__violin__public_stage.name}/XXX/' file_format = (TYPE = 'PARQUET');"
  database       = "RAW"
  name           = "VIOLIN__PUBLIC_STAGE_XXX_PIPE"
  schema         = "VIOLIN__PUBLIC"
  comment        = "Owner: Data Team; Terraform: true"
}
```

tables names have been redacted\*

**Additional context**

resources seem to be created fine.

**Comment by robbruce** [comment]
@sortigoza the issue is that when you include a `;` at the end of your COPY statement, snowflake does not include that character in the result of `SHOW PIPE`. You can also face the same issue if `\r\n` was used in the copy statement, as snowflake will use `\n` line endings.

Will issue a pull request a fix as we've faced this before in our own provider.

**Comment by sortigoza** [comment]
Thank you @ryanking !!
