### ISSUE TITLE
snowflake_provider snowflake_database_grant constantly being recreated

### ISSUE THREAD

**Issue by funes79** [chanzuckerberg/terraform-provider-snowflake#248]
**Provider Version**

The provider version you are using 0.15

**Terraform Version**

The version of Terraform you were using when the bug was encountered. 0.13.1

**Describe the bug**

Terraform tries to drop and create always this resource. When I apply the changes and run plan again, get the same change, 1 to add and 1 to destroy.

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # snowflake_database_grant.dev_to_security_admin must be replaced
-/+ resource "snowflake_database_grant" "dev_to_security_admin" {
        database_name     = "DEV_DB"
      ~ id                = "DEV_DB|||ALL|false" -> (known after apply)
        privilege         = "ALL"
      ~ roles             = [ # forces replacement
          + "SECURITYADMIN",
        ]
      - shares            = [] -> null
        with_grant_option = false
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

The resource:
```
resource "snowflake_database_grant" "dev_to_security_admin" {
  database_name = snowflake_database.dev_db.name
  privilege     = "ALL"
  roles         = ["SECURITYADMIN"]
  shares        = []
}
```

**Expected behavior**
It should grant ALL on the database to SECURITYADMIN only **once**

**Code samples and commands**

Please add code examples and commands that were run to cause the problem.

**Additional context**

The state (tfstate file) looks like this when the plan wants to change the resource:

```
    {
      "mode": "managed",
      "type": "snowflake_database_grant",
      "name": "dev_to_security_admin",
      "provider": "provider.snowflake",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "database_name": "DEV_DB",
            "id": "DEV_DB|||ALL|false",
            "privilege": "ALL",
            "roles": [
              "SECURITYADMIN"
            ],
            "shares": null,
            "with_grant_option": false
          },
          "private": "bnVsbA==",
          "dependencies": [
            "snowflake_database.dev_db"
          ]
        }
      ]
    },
```
So it looks to me that a plan is wrong. Because in the plan it says the roles array must be changed to add +SECURITYADMIN.

```
~ roles             = [ # forces replacement
          + "SECURITYADMIN",
        ]
      - shares            = [] -> null
```

**Comment by slocke716** [comment]
We are also plagued by the same bug. It is causing a lot of issues since it will drop USAGE grants on the database every time we run terraform against snowflake

**Comment by funes79** [comment]
I think I know what is the problem here. The ALL privilege in Snowflake does not exists. Actually when you grant ALL, it is just a placeholder like asterix, that any privilege what can be applied on that object type, you grant it. And I think the provider has the confusion there, because when you grant and then SHOW GRANTs you **DO NOT SEE ALL PRIVILEGE** in the result set. 

So in my case I grant ALL in one place for Role X. But then I grant USAGE (for the same object) in another place for Role Y and Z.

So terraform does a plan:
+ ALL for Role X 
+ USAGE for Role Z and Y

But then another apply is run and what the provider gets from the database is this:
RoleX has USAGE, CREATE, ETC ETC.
RoleZ has USAGE
RoleY has USAGE

So if I pivot this: USAGE = [RoleX, RoleZ, RoleY]
                           CREATE = [RoleX]
                          ...

So then obviously there are 3(!) roles granted to USAGE instead of two roles in the tf file. So it plans:
- USAGE for Role X

And this goes on and on.

I did not inspect the code, but I think this is the reason why these ALL priviliges are triggering recreate.

**Comment by ahaffar** [comment]
i solved this by adding a lifecycle to the resource 
```
  lifecycle {
    ignore_changes = [
      roles,
    ]
  }
```

**Comment by funes79** [comment]
That would not help me because for obvious reasons I do not want to ignore when a new role has been added or removed from a specific resource and permission (for example schema RAW permission USAGE)
I think the ideal solution would be if the provider would support this ALL (asterix) mapping to specific permissions, i..e if there would be hard-coded in the code what ALL means for different resource types (i.e. what are the privileges ALL on schema, what does ALL mean on database, etc.)
In that way the provider could do a smart provisioning of resources and we would just write one grant resource.

But until this comes, we need to explicitly write resource grant for EVERY permission, like CREATE TABLEL, USAGE, CREATE MATERIALIZED VIEW etc etc etc.
