### ISSUE TITLE
snowflake schema recreate does not trigger grants and views recreate

### ISSUE THREAD

**Issue by funes79** [chanzuckerberg/terraform-provider-snowflake#249]
**Provider Version**

0.15

**Terraform Version**

0.13.1

**Describe the bug**

Schemas are defined in variables:
```
variable "dev_schemas" {
  description = "Schema names, comments and role settings for DEV"
  default = {
    "RAW" = {
      comment      = "contains raw data"
      usage_roles  = []
      all_roles    = ["ENGINEER_DEV"]
      is_transient = true
    }
   # etc etc
}
```
Having a schema defined as a dynamic list of resources:
```
resource "snowflake_schema" "dev_schemas" {
  for_each     = var.dev_schemas
  name         = each.key
  database     = snowflake_database.dev_db.name
  comment      = each.value.comment
  is_transient = each.value.is_transient
  depends_on   = [snowflake_database.dev_db]
}
```
Grants:
```
resource "snowflake_schema_grant" "schema_grant_dev_db_usage" {
  for_each      = var.dev_schemas
  schema_name   = each.key
  database_name = "DEV_DB"
  privilege     = "USAGE"
  roles         = each.value.usage_roles != [] ? each.value.usage_roles : ["ALL"]
  shares        = []
  depends_on    = [snowflake_schema.dev_schemas, snowflake_role.role]
}
```
Views:
```
resource "snowflake_view" "raw_views" {
  for_each   = fileset("${path.module}/raw_views", "*.sql")
  database   = snowflake_database.dev_db.name
  schema     = snowflake_schema.dev_schemas["RAW"].name
  name       = upper(replace(replace(each.value, ".sql", ""), ".", ""))
  statement  = file("${path.module}/raw_views/${each.value}")
  depends_on = [snowflake_schema.dev_schemas["RAW"]]
}
```
When I change the `is_transient` property of the RAW schema into false, the provider (correctly) plans a destroy and create of the schema. **But the provider ignores that schema has been granted to roles and that schema has been used in views**

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # snowflake_schema.dev_schemas["RAW"] must be replaced
-/+ resource "snowflake_schema" "dev_schemas" {
        comment             = "contains raw data from our source systems"
        data_retention_days = 1
        database            = "DEV_DB"
      ~ id                  = "DEV_DB|RAW" -> (known after apply)
        is_managed          = false
      ~ is_transient        = true -> false # forces replacement
        name                = "RAW"
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

Thus these grants and views suddenly dissapear.
In the next terraform apply the provider realizes that the grants and views are missing, trying to re-create.

**Expected behavior**

It should analyze the dependency and re-create all the downstream (or child) resources of the schema - specially grants and views.

**Code samples and commands**

Please add code examples and commands that were run to cause the problem.

**Additional context**

**Comment by foresterr** [comment]
I observed something similar with warehouses and warehouse grants.

I think what's needed to solve this is to mark the name as something that always changes when recreating (even if it actually stays the same), as this would cause terraform to properly detect any cascading dependencies. Of course I don't know enough about writing terraform providers to know if this is possible ;)

In case of warehouses, I got around this by using id instead of name, which for warehouse is the same (because id is always "known after apply" when recreating), but for schemas id includes other things in addition to the name. If you need a quick workaround, I guess you could use split() to parse the id in the dependent resources instead of using name or key.

**Comment by funes79** [comment]
@foresterr can you be more specific how this workaround works with Id's? Perhaps and example on the warehouse and warehouse grant resources. Thank you

**Comment by foresterr** [comment]
I think in your case grant resource would have to look something like this:
```
resource "snowflake_schema_grant" "schema_grant_dev_db_usage" {
  for_each      = var.dev_schemas
  schema_name   = split(snowflake_schema.dev_schemas[each.key].id, '|')[1] #this is the important part
  database_name = "DEV_DB"
  privilege     = "USAGE"
  roles         = each.value.usage_roles != [] ? each.value.usage_roles : ["ALL"]
}
```
Resource id is something that is always marked as changed when a resource is recreated, so if it's used somewhere in another resource, it triggers the dependency. For schemas, if name stays the same during the recreation, it is not marked as changed (you can see that in the plan output), so if there are other resources referring to it, they don't detect any change and assume they don't need to be recreated.

**Comment by funes79** [comment]
Thanks, this looks like a solution for this problem!
