### ISSUE TITLE
Passphrase for private key

### ISSUE THREAD

**Issue by funes79** [chanzuckerberg/terraform-provider-snowflake#251]
Hi contributors!
 would it be possible to add a passphrase support for private key authentication? 
Because the existing Snowsql documentation requires an encrypted private key, and here the provider requires a non-encrypted key. 

https://docs.snowflake.com/en/user-guide/snowsql-start.html
_The private key file must be encrypted,  and the passphrase must be specified in the environment variable SNOWSQL_PRIVATE_KEY_PASSPHRASE_

Thank you!

**Comment by robbruce** [comment]
@funes79 I agree, it gets a little complicated as snowsql expects a key to be in PKCS8 format whereas currently this provider only supports PEM. Also in addition, have the option to extract credentials for a defined connection in the users `~/.snowsql/config` file (or Windows equivalent)

**Comment by funes79** [comment]
> whereas currently this provider only supports PEM

@robbruce I mean this provider support PKSC8 (I tested) but just it does not work with password protected PKSC8,
so I had to use *nocrypt* during private key creation.

```
openssl genrsa 2048 | openssl pkcs8 -topk8 -inform PEM -out rsa_key.p8 -nocrypt
openssl rsa -in rsa_key.p8 -pubout -out rsa_key.pub
```

**Comment by ryanking** [comment]
@funes79 I think we could only support passphrases if the passphrase is passed in as a configuration option to the provider configuration.

**Comment by funes79** [comment]
I would also 👍 for the passphrase provided by environment variable. In workflows I would like to provide it in the runtime, rather than storing it in the terraform tf files. Thank you!

**Comment by troszok** [comment]
IMHO environment variable for passphrase is the way to go. 
Is this feature somewhere on your roadmap?

**Comment by advaitvdeo** [comment]
Hi, Does it support passphrase in configuration option ?
Because from the documentation, I dont see passphrase as a parameter in provider configuration - https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs#authentication

If not, do we have a release date for this feature ? Currently we are not able to use key/pair because it does not accept passphrase.
