### ISSUE TITLE
Can we cut a new release please!

### ISSUE THREAD

**Issue by AClarkie** [chanzuckerberg/terraform-provider-snowflake#258]
**Is your feature request related to a problem? Please describe.**

I would like a new github release that includes the following PR:
https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/252

My workaround is to build the binary myself but rolling that process into a docker build is a bit dangerous. Can we cut a new release please!

**Comment by ryanking** [comment]
Yes, our release tools is currently broken. Once fixed we will get one out, hopefully next week sometime.
