### ISSUE TITLE
Grant DB access to a role

### ISSUE THREAD

**Issue by StevenR152** [chanzuckerberg/terraform-provider-snowflake#26]
Is there a way to use this provider to do the following:

GRANT USAGE on DATABASE <DB_NAME> to <ROLE_NAME>;

GRANT MODIFY on DATABASE <DB_NAME> to <ROLE_NAME>;

**Comment by sjauld** [comment]
I have a few more GRANT requirements, including
```
GRANT USAGE on SCHEMA <schema> to SHARE <share>;
GRANT SELECT on VIEW <view> to SHARE <share>;
 ```

Would it make sense to create a grant_generic.go in the snowflake package? Currently there's a RoleGrantBuilder that does
```
GRANT ROLE <role> to ROLE <role>;
GRANT ROLE <role> to USER <user>;
```
But I guess this could become a GrantBuilder that does
```
GRANT <object/permissions> [<objectName>] [on <object> <objectName>] to <object> <objectName>;
```

**Comment by ryanking** [comment]
Yeah my plan here is to build a resource that grants privileges to roles exclusively. This should be able to cover all privileges granted to roles. Going to be working on this later this week and next.
