### ISSUE TITLE
snowflake_schema_grant multiple privileges

### ISSUE THREAD

**Issue by ahaffar** [chanzuckerberg/terraform-provider-snowflake#260]
**Provider Version**
0.15.0

**Terraform Version**
0.13.0

**Describe the bug**
snowflake_schema_grant privilege is limited to string 
**Expected behavior**
it should allow passing a string with multiple values such as `Monitor, Usage`
it should allow passing a string with multiple values such as `Monitor, Usage`
**Code samples and commands**

Please add code examples and commands that were run to cause the problem.
```
resource "snowflake_schema_grant" "RAW" {
database = snowflake_database.database.name
roles = toset([snowflake_role.role.name])
schema = snowflake_schema.schema.name
privilege = "USAGE, MONITOR"
}
```
**Additional context**
`Error: expected privilege to be one of [ALL MODIFY MONITOR CREATE VIEW CREATE FUNCTION CREATE EXTERNAL TABLE OWNERSHIP USAGE CREATE STAGE CREATE SEQUENCE CREATE PROCEDURE CREATE PIPE CREATE STREAM CREATE TASK CREATE TEMPORARY TABLE CREATE TABLE CREATE FILE FORMAT CREATE MATERIALIZED VIEW], got MONITOR, USAGE`

**Comment by funes79** [comment]
This is afaik not a bug, according to the documentation https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs/resources/schema_grant the grant takes only one privilege. So in your case you need to write:
```
resource "snowflake_schema_grant" "RAW_USAGE" {
database = snowflake_database.database.name
roles = toset([snowflake_role.role.name])
schema = snowflake_schema.schema.name
privilege = "USAGE"
}
resource "snowflake_schema_grant" "RAW_MONITOR" {
database = snowflake_database.database.name
roles = toset([snowflake_role.role.name])
schema = snowflake_schema.schema.name
privilege = "MONITOR"
}
```

**Comment by ryanking** [comment]
As @funes79 says, this is the way it is intended to work.

**Comment by vickyjkwan** [comment]
I found a work around by applying `for_each` to a TF `variable` block that's being assigned an array. 

```
# create role
resource "snowflake_role" "role" {
  name    = "ROLE_NAME"
}

# generate list type variable to include all privileges that the role needs on schema level
variable "schema_privileges" {
  default = ["USAGE", "CREATE TABLE"]
}

# grant schema access to role
resource "snowflake_schema_grant" "grant" {
  database_name = "db_name"
  schema_name   = "schema_name"

  for_each  = toset(var.schema_privileges)
  privilege = each.value

  roles = [snowflake_role.role.name]
}

**Comment by kallangerard** [comment]
Whether you call it a bug or something else is just semantics. The provider isn't aligning to the underlying infrastructure, which supports multiple comma separated privileges on a grant. This also results in an explosion of Terraform resources where the number is privileges * grant object.

**Comment by ryan-groove** [comment]
> I found a work around by applying `for_each` to a TF `variable` block that's being assigned an array.
> 
> ```
> # create role
> resource "snowflake_role" "role" {
>   name    = "ROLE_NAME"
> }
> 
> # generate list type variable to include all privileges that the role needs on schema level
> variable "schema_privileges" {
>   default = ["USAGE", "CREATE TABLE"]
> }
> 
> # grant schema access to role
> resource "snowflake_schema_grant" "grant" {
>   database_name = "db_name"
>   schema_name   = "schema_name"
> 
>   for_each  = toset(var.schema_privileges)
>   privilege = each.value
> 
>   roles = [snowflake_role.role.name]
> }
> ```

When I run a similar script, I've noticed the last privilege grant is the only one applied.  So for this example, CREATE TABLE privilege would be the only privilege applied.  Does this actually work for you?  If you run, `show grants on schema db_name.schema_name` do you see both privileges?

**Comment by rumbin** [comment]
@ryan-groove there seems to be a bug report for the issue you observed: https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1610
