### ISSUE TITLE
Database name update doesn't update the references in other resources

### ISSUE THREAD

**Issue by chamilad** [chanzuckerberg/terraform-provider-snowflake#266]
**Provider Version**

0.16.0

**Terraform Version**

v0.13.3

**Describe the bug**
1. Create a `snowflake_database` with name `db01`
2. Create a `snowflake_schema` and `snowflake_stage` attached to `db01` database
3. Change the database name to `db02`, and schema and stage names to new names and run `terraform apply`
4. Database gets updated, but when it comes to updating schema and stage, an error message `Database  "db01" does not exist` is shown.
5. Edit the file `terraform.tfstate` manually and replace the references to `db01` with `db02` and rerun `terraform apply`
6. Resources get updated successfully.

**Expected behavior**

1. Create a `snowflake_database` with name `db01`
2. Create a `snowflake_schema` and `snowflake_stage` attached to `db01` database
3. Change the database name to `db02`, and schema and stage names to new names and run `terraform apply`
4. All resources get updated at the same time without an issue.

**Code samples and commands**

Above description might provide enough information. 

**Additional context**

The IDs of the other resources that refer to databases should be updated when an update happens to database resources. I was not able to find a good example of where this happens at the moment in other providers.

**Comment by funes79** [comment]
I think the problem is in the fact that the ID contains the database name (in many resources). And to replace ID terraform has to re-create, so you would loose your schema (and data) if the provider runs `DROP SCHEMA ...; CREATE SCHEMA...`

This is kind of unfortunate - but afaik Snowflake does not provide unique object IDs like Microsoft SQL Server - where you would be able to assign for every table, schema, database a unique number.

**Comment by ryanking** [comment]
I think @funes79 is right on this one. If you disagree @chamilad, some example code would be helpful.

**Comment by funes79** [comment]
Maybe we should ask Snowflake to expose their object id's via some system level table or view or function call (Like Microsoft does here https://docs.microsoft.com/en-us/sql/t-sql/functions/object-id-transact-sql?view=sql-server-ver15) and then we could rewrite the whole provider to use those :-)

**Comment by ryanking** [comment]
@funes79 that would be very helpful, for sure

**Comment by chamilad** [comment]
Thinking about this more, I think I agree with your idea on this is @funes79 @ryanking .  As an outcome of this issue, should this behavior be documented (if not already done)?
