### ISSUE TITLE
[feature] creating tables

### ISSUE THREAD

**Issue by skynet008** [chanzuckerberg/terraform-provider-snowflake#269]
Hi,

It would be very useful to be able to create tables using this terraform provider. That will be super handy to implement DevOps CI/CD practices on Snowflake project.

Any plan to have that ? Any particular challenges with implementing such a feature ?

Cheers

**Comment by ryanking** [comment]
https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/242
