### ISSUE TITLE
snowflake_table is currently unusable due to column field

### ISSUE THREAD

**Issue by dimon37** [chanzuckerberg/terraform-provider-snowflake#272]
**0.17.1** - The provider version you are using.

**Terraform v0.13.4** The version of Terraform you were using when the bug was encountered.

**snowflake_table is unusable**

I am trying to use the newly-released resource, however I'm getting error all the time.
When I define my table like this:
```
resource "snowflake_table" "incident_ingest"{
	database = "DB_DEV3_TF"
	schema = "RAW"
	name = "incident_ingest"
	column = {
        name = "payload"
        type = "variant"
      }
}
```
I get the following error:
```
Error: Unsupported argument

  on 07_snowpipe_incident.tf line 5, in resource "snowflake_table" "incident_ingest":
   5: 	column = {

An argument named "column" is not expected here. Did you mean to define a
block of type "column"?
```
If I remove column field, I get the missing argument error:
`Error: "column": required field is not set`

I tried experimenting with different formats for the column field, but I always get "unsupported argument"

**Comment by iserko** [comment]
@dimon37 try

```
resource "snowflake_table" "incident_ingest" {
  database = "DB_DEV3_TF"
  schema = "RAW"
  name = "incident_ingest"
  column {
    name = "payload"
    type = "variant"
  }
}
```

Docs are lacking, but I used the PR's description https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/242 to figure it out for myself.

**Comment by dimon37** [comment]
OK, that works. Just in case, I confirmed that column block can be repeated to create multiple columns.
Is there a way of setting primary key or other meta objects? Indexes? Constraints?

**Comment by ryanking** [comment]
@dimon37 Those are not supported yet, but PRs are welcome.
