### ISSUE TITLE
Question: exclusive grants clarification

### ISSUE THREAD

**Issue by aaronsteers** [chanzuckerberg/terraform-provider-snowflake#283]
The documentation states that all grants for a schema/table must be managed by a single resource declaration:

> Note: The snowflake_table_grant resource creates exclusive attachments of grants. Across the entire Snowflake account, all of the tables to which a single grant is attached must be declared by a single snowflake_table_grant resource. This means that even any snowflake_table that have the attached grant via any other mechanism (including other Terraform resources) will have that attached grant revoked by this resource. These resources do not enforce exclusive attachment of a grant, it is the user's responsibility to enforce this.

However, what about granting different kinds of grants to different roles? We should be able to grant one role read access and another role read-write access, yes? Presumably that would require more than one resource declaration to managing the same table or schema. Can someone confirm this is indeed supported?

**Comment by funes79** [comment]
Hi, let me try to explain: 
Short answer is yes you are able to grant read only (ro) to one set of roles and read write to another set of roles. BUT:
In snowflake the ro and rw are not distinct privileges right. Lets simplify table access to: 
SELECT = read only
INSERT UPDATE DELETE AND SELECT = readwrite.

This exclusivity means that you must not create two separate resources for Select priv. 

So you have to create 1 resource grant for SELECT (ro) and **put here ro AND rw roles**
and 3 resources to grant the write privileges to the rw role(s).

**Comment by aaronsteers** [comment]
Got it - thank you!
