### ISSUE TITLE
Pipes in different schemas, but with same name are tainted by each other.

### ISSUE THREAD

**Issue by elliottohara** [chanzuckerberg/terraform-provider-snowflake#290]
**Provider Version**

0.17.1

**Terraform Version**

0.12.x

**Describe the bug**

Pipes in different schemas, but with the same name are tainted by each other. 
In our use case, we use workspaces to segregate our alpha from prod resources. We put our alpha pipes in `RAW.ALPHA__SNOWPIPE_S3` and our prod pipes in `RAW.SNOWPIPE_S3`. 

When a run a `terraform plan` in my prod workspace, it sees the resources in `RAW.ALPHA__SNOWPIPE` as tainted (likely because they come back in alphabetical order?). 
 
**Expected behavior**

Pipes should respect schema when checking state.

**Code samples and commands**
See explanation above. 

**Additional context**

**Comment by ryanking** [comment]
This appears to have been fixed by #291
