### ISSUE TITLE
Create resource snowflake_sql_script as failsafe for unsupported features

### ISSUE THREAD

**Issue by aidanmelen** [chanzuckerberg/terraform-provider-snowflake#292]
**Is your feature request related to a problem? Please describe.**

First things first, hats off to the maintainers for creating an awesome provider.

That being said, there are many features that I would like for this provider to support; such as granting all for all tables/schemas/futures or security integrations.

As a result, I am having to manually run commands like these to grant broad access to database tables and schemas:

```sql
-- grants.sql
-- table
GRANT SELECT ON ALL TABLES IN DATABASE MY_DATABASE TO ROLE MY_ROLE;
GRANT SELECT ON ALL VIEWS IN DATABASE MY_DATABASE TO ROLE MY_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE MY_DATABASE TO ROLE MY_ROLE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE MY_DATABASE TO ROLE MY_ROLE;

-- schema
GRANT ALL ON ALL SCHEMAS IN DATABASE MY_DATABASE TO ROLE MY_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE MY_DATABASE TO ROLE MY_ROLE;
```

Today, this is simply not feasible to manage these statements with this provider. [I know I am not alone by manually running these commands along side the terraform](https://youtu.be/r4tAyiTgwRw?t=1703).

**Describe the solution you'd like**

I would like to create a failsafe resource that simply makes the user of the provider responsible for ensuring the CRUD logic with raw `snowsql` statements. I would call this the `snowflake_sql_script` resource and it would work similar to the [terraform-provider-shell](https://github.com/scottwinkler/terraform-provider-shell#using-the-provider). For example, I could have terraform manage one or many of the commands specified above e.g.

```hcl
resource "snowflake_sql_script" "grant-all-on-all-tables-in-database" {
  create = "GRANT SELECT ON ALL TABLES IN DATABASE MY_DATABASE TO ROLE MY_ROLE;"
  delete = "REVOKE SELECT ON ALL TABLES IN DATABASE MY_DATABASE ON ROLE MY_ROLE;"
}
```

This would give this provider a broad interface to run any Snowflake sql statement(s) and still have Terraform manage the CRUD operations.

**Describe alternatives you've considered**

I have tried using `table_grants` and `schema_grants` resources and they do not support my use case

**Additional context**

So why don't I just fix the `table_grants` and `schema_grants` resources like is [being attempted here in this pull request](https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/141)?!? Well, this isn't the only missing feature that I am having to run manual sql statements to fill in the gaps left behind by this provider. I could use the `snowflake_sql` to create a security integration or whatever new features snowflake offers that is not supported by this module.

I don't think this resource should be the first thing that users will reach for e.g. it would be counter productive to use the `snowflake_sql-script` resource like this:

```hcl
resource "snowflake_sql_script" "grant-all-on-all-tables-in-database" {
  create = "CREATE ROLE 'MY_ROLE';"
  delete = "DROP ROLE IF EXISTS 'MY_ROLE';"
}
```

But you could... Instead we would be more robust and simple to use the `snowflake_role` resource like this:

```hcl
resource "snowflake_role" "role" {
  name    = "MY_ROLE"
}
```

**Comment by aidanmelen** [comment]
I am going to look into starting a PR this weekend, but I will likely need to help from the community on this one. We will see how far I get.

**Comment by aidanmelen** [comment]
@ryanking is this something that you would approve?

**Comment by aidanmelen** [comment]
It would be inappropriate to use the `snowflake_sql_script` to manage a database, warehouse, role, or any other resource that is supported by this provider. These purpose built provider resources are more robust and are designed to handle the CRUD logic for a specific snowflake objects. Although you could use the `snowflake_sql_script` to managing these snowflake objects, it is not recommended. I created this provider resources to handle the situations and use cases that are unsupported by existing functionality. As a result, operators of this provider are required to deviate from the IaC by maintaining a few sql scripts to live along side the Terraform. Below are some examples of how operators of this provider may use the `snowflake_sql_script` resource to manage the lifecycle of snowflake objects:

1. If you have a OKTA integrated Snowflake account, then OKTA SCIM will automatically push over OKTA groups and users to corresponding Snowflake roles and users. This works great until you declare (in Terraform) to grant a TF managed service user to the OKTA SCIM managed role. The `snowflake_role_grant` resource will do what it is suppose to do, ensure that Terraform manages the grants to users for a specific role. As a result, Terraform will revoke the grants for all users granted by OKTA SCIM and will add the Terraform service users declared in Terraform. By having the `snowflake_sql_script` we could manage specific grants to a role without blowing away grants managed by OKTA SCIM.

2. It is a best practice to have all custom roles roll up into the `SYSADMIN` role as defined in the [Creating a Role Hierarchy](https://docs.snowflake.com/en/user-guide/security-access-control-configure.html#creating-a-role-hierarchy) Snowflake documentation. Just like (1), if you attempt to add a role grant to `SYSADMIN` from a role that is managed by OKTA SCIM, the Terraform will want to blow away all the user and role grants on that role. The `snowflake_sql_script` will allow admins to declare a subset of role grants for a non-terraform managed role and achieve a role hierarchy managed by Terraform.

3. The [OKTA SCIM integration requires a Snowflake Security Integration](https://docs.snowflake.com/en/user-guide/scim-okta.html#snowflake-configuration) which is currently unsupported by this provider. The Snowflake Security Integration is not a widely used resource and someone who wants it could be waiting a long time. The `snowflake_sql_script` provides a failsafe for missing features in this provider and allows users to manage their entire Snowflake Account with Terraform and not just the objects that are supported.

4. As Snowflake adds new objects, this provider will be able to manage them as soon as they are available to the console. e.g.
- [snowflake security integration](https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/277)
- snowflake organizations (BETA)
- [Streams and Tasks support](https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/157)
etc

5. Allow operators to manage a bundle of grants that would otherwise require many snowflake resources to declare the grants:
- `GRANT ALL ON ALL SCHEMAS IN DATABASE db TO ROLE role;`
- `GRANT ALL ON ALL FUTURE SCHEMA IN DATABASE db TO ROLE role;`
- `GRANT ALL ON ALL TABLES IN DATABASE db TO ROLE role;`
- `GRANT ALL ON ALL FUTURE TABLES IN DATABASE db TO ROLE role;`
- `GRANT ALL ON ALL VIEWS IN DATABASE db TO ROLE role;`
- `GRANT ALL ON ALL FUTURE VIEWS IN DATABASE db TO ROLE role;`

6. Bundling common grants with a single resource declaration. Consider this Terraform project layout:

```
snowflake
├── bin
│   ├── grants_create.sql
│   └── grants_delete.sql
└── main.tf
```

where the sql scripts contain the following content:

**grants_create.sql**
```sql
-- The snowflake_sql_script will use the as the 'C' in CRUD
GRANT ALL ON ALL SCHEMAS IN DATABASE db TO ROLE role;
GRANT ALL ON ALL FUTURE SCHEMA IN DATABASE db TO ROLE role;
GRANT ALL ON ALL TABLES IN DATABASE db TO ROLE role;
GRANT ALL ON ALL FUTURE TABLES IN DATABASE db TO ROLE role;
GRANT ALL ON ALL VIEWS IN DATABASE db TO ROLE role;
GRANT ALL ON ALL FUTURE VIEWS IN DATABASE db TO ROLE role;
```

**grants_delete.sql**
```sql
-- The snowflake_sql_script will use the as the 'D' in CRUD
REVOKE ALL ON ALL SCHEMAS IN DATABASE db ON ROLE role;
REVOKE ALL ON ALL FUTURE SCHEMA IN DATABASE db ON ROLE role;
REVOKE ALL ON ALL TABLES IN DATABASE db ON ROLE role;
REVOKE ALL ON ALL FUTURE TABLES IN DATABASE db ON ROLE role;
REVOKE ALL ON ALL VIEWS IN DATABASE db ON ROLE role;
REVOKE ALL ON ALL FUTURE VIEWS IN DATABASE db ON ROLE role;
```

then we can utilize the scripts in the `snowflake_sql_script` declaration:

```hcl
resource "snowflake_sql_script" "script" {
  name = "GRANT_VERBOSE_ACCESS"
  lifecycle_commands {
    create = file("${path.module}/bin/grants_create.sql")
    delete = file("${path.module}/bin/grants_delete.sql")
  }
}
```

In this way, we can write our CRUD logic in native SQL scripts and we can declare the orchestration of CRUD operations in just a few lines of Terraform.

**Comment by vince5678** [comment]
Hello @aidanmelen, this is what we did for resources not yet supported by the snowflake provider using terraform `null_resource `and `snowsql`.
In you snowsql config, add exit_on_error = True otherwise when the sql fails you will not get the error.

```
resource "null_resource" "pipe" {

  triggers = {
    schema_name = var.schema
    database_name = var.database_name
    name = "PIPE_${local.schema}_${local.table_name}"
    statement = var.copy_statement
  }

  provisioner "local-exec" {
    on_failure = fail
    interpreter = [
      "/bin/bash",
      "-c"]
    command = <<CMD
sql=$(cat <<-END
CREATE PIPE "${self.triggers.database_name}"."${self.triggers.schema_name}"."${self.triggers.name}" AS ${self.triggers.statement};
END
);
snowsql --config $SNOWSQL_CONFIG -q "$sql";
[[ $? != 0 ]] && exit 1 || exit 0
CMD
  }

  provisioner "local-exec" {
    when = destroy
    on_failure = continue
    interpreter = [
      "/bin/bash",
      "-c"]
    command = <<CMD
sql=$(cat <<-END
DROP PIPE "${self.triggers.database_name}"."${self.triggers.schema_name}"."${self.triggers.name}";
END
);
snowsql --config $SNOWSQL_CONFIG -q "$sql";
[[ $? != 0 ]] && exit 1 || exit 0
CMD
  }
}
```

**Comment by aidanmelen** [comment]
Hey @vince5678, I really like your example using the `local-exec` provider! Pretty impressive if you got that to work. One problem for me is that I would like to run my Terraform remotely in Terraform Cloud where the `snowsql` cli tool is not available at runtime...


That being said, I just created a provider that allows us to declare arbitrary SnowSQL statements such as `GRANT ALL` in Terraform! This uses the snowflake Golang library so we do not need to depend on the `snowsql` binary being available on the host machine at runtime. Here is a code snippet from the [terraform-provider-snowsql/examples/simple/main.tf](https://github.com/aidanmelen/terraform-provider-snowsql/blob/main/examples/simple/main.tf#L66-L84).

```hcl
resource "snowsql_exec" "dcl" {
  name = local.name

  create {
    statements = <<-EOT
    GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE ${snowflake_database.database.name} TO ROLE ${snowflake_role.role.name};
    GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE ${snowflake_database.database.name} TO ROLE ${snowflake_role.role.name};
    EOT
  }

  delete {
    statements = <<-EOT
    REVOKE ALL PRIVILEGES ON ALL TABLES IN DATABASE ${snowflake_database.database.name} FROM ROLE ${snowflake_role.role.name};
    REVOKE ALL PRIVILEGES ON FUTURE TABLES IN DATABASE ${snowflake_database.database.name} FROM ROLE ${snowflake_role.role.name};
    EOT
  }

  delete_on_create = true
}
```

Check out the [terraform-provider-snowsql snowsql_exec resource documentation](https://registry.terraform.io/providers/aidanmelen/snowsql/latest/docs/resources/exec) for more information.

**Comment by afeld** [comment]
FYI that there's (now?) a [`snowflake_unsafe_execute`](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/unsafe_execute) resource.
