### ISSUE TITLE
Canonical Snowflake provider

### ISSUE THREAD

**Issue by sjauld** [chanzuckerberg/terraform-provider-snowflake#32]
It seems like there are three active providers:

- https://github.com/chanzuckerberg/terraform-provider-snowflake
- https://github.com/Preston4tw/terraform-provider-snowflake
- https://github.com/ShopRunner/terraform-provider-snowflake

Any chance of the three of you combining efforts? I want to contribute but first I'll need to work out which one is close enough to what I need (all three are missing different bits and pieces).

**Comment by ryanking** [comment]
I would be happy to work with others on this, but before starting our implementation I looked at those two and they didn't seem very active.

FWIW we are already using ours in production and are just getting started.

**Comment by sjauld** [comment]
Thanks @ryanking. Preston4tw confirmed that his repo is unmaintained, and ShopRunner doesn't seem to be in a great state, so I'll log some issues here and try to help build out some more resources.
