### ISSUE TITLE
Add an optional role to use when creating users and roles

### ISSUE THREAD

**Issue by slocke716** [chanzuckerberg/terraform-provider-snowflake#372]
This is not really a problem but a work-around that we currently need to implement to integrate with permifrost. Permifrost rightfully expects the securityadmin to be able alter any attributes of users and roles, however, since currently we can only define a single role for all tasks in terraform our roles and users are owned by accountadmin on creation. This means we run sql to alter the ownership before running the permifrost.

Ideally all of all resources could take an optional "apply role" but minimally users and roles would have that optional param.

**Comment by ryanking** [comment]
> since currently we can only define a single role for all tasks in terraform

Not sure what you mean by this. Can you clarify?

**Comment by slocke716** [comment]
Sure. As far as I know https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/main/examples/provider/provider.tf#L13 this is the only location that you can set the role that the terraform user runs as. I'd like to be able to default to that but have an optional param in the resource definitions to define an alternate role.

**Comment by ryanking** [comment]
I think you can achieve what you want with the provider as it is by having [multiple, aliased provider configurations](https://www.terraform.io/docs/configuration/providers.html#alias-multiple-provider-configurations)–


```terraform
provider snowflake {
  alias = "securityadmin"
  role = "SECURITYADMIN"
  ...
}

provider snowflake {
  alias = "accountadmin"
  role = "ACCOUNTADMIN"
  ...
}


resource snowflake_role a {
  ...
  provider = snowflake.securityadmin
}

resource snowflake_role b {
  ...
  provider = snowflake.accountadmin
}

```

**Comment by ryanking** [comment]
Closing, feel free to re-open if this doesn't solve the problem.

**Comment by slocke716** [comment]
This is wonderful! Thank you so much. I had not thought to do that.
