### ISSUE TITLE
resource type "snowflake_integratin_grant" not found

### ISSUE THREAD

**Issue by yohei1126** [chanzuckerberg/terraform-provider-snowflake#375]
**Provider Version**

0.20.0

**Terraform Version**

v0.14.3

**Describe the bug**

Terraform snowflake plugin does not support resource type `snowflake_integratin_grant`.

```
$ terraform plan --out out.tfplan
Releasing state lock. This may take a few moments...

Error: Invalid resource type

  on storage_integration.tf line 11, in resource "snowflake_integratin_grant" "storage_int_s3_landing":
  11: resource snowflake_integratin_grant storage_int_s3_landing {

The provider provider.snowflake does not support resource type
"snowflake_integratin_grant".
```

**Expected behavior**

Terraform snowflake plugin should support resource type `snowflake_integratin_grant`.

**Code samples and commands**

This code cause the issue.

```
resource snowflake_integratin_grant storage_int_s3_landing {
  integration_name = "storage_int_s3_landing"
  privilege = "USAGE"
  roles     = ["TERRAFORM", "SYSADMIN"]
  with_grant_option = false
}
```

**Additional context**

**Comment by ryanking** [comment]
It appears you have a typo in your code– `s/snowflake_integratin_grant/snowflake_integration_grant/g`.

**Comment by yohei1126** [comment]
I just copy from your document so our document is the root cause of the issue. Will send a PR to fix it.

**Comment by yohei1126** [comment]
@ryanking Raised a PR to fix this typo. https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/378/files
