### ISSUE TITLE
Spelling mistake in documentation for "snowflake_integratin_grant"

### ISSUE THREAD

**Issue by jifeous** [chanzuckerberg/terraform-provider-snowflake#377]
In the documentation the integration grant is missing an "o".

https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs/resources/integration_grant

resource snowflake_integratin_grant grant {
...

**Comment by yohei1126** [comment]
@jifeous This issue has already been fixed. https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/378

**Comment by jifeous** [comment]
fixed in #378
