### ISSUE TITLE
snowflake_table resource applying a data type different from the specified data type

### ISSUE THREAD

**Issue by sfc-gh-dsandler** [chanzuckerberg/terraform-provider-snowflake#422]
The following Terraform apply:

```
resource "snowflake_table" "my_tbl" {
  name     = "MYTBL"
  database = "MYDB"
  schema   = "MYSCHEMA"
  column   {
            name = "COLUMN1" 
            type = "SMALLINT" 
  } 
  comment  = "test table"

  depends_on = [snowflake_schema.schema]
}
```

produces a table with a NUMBER instead of a INT data type.  

While [synonymous with NUMBER,](https://docs.snowflake.com/en/sql-reference/data-types-numeric.html#int-integer-bigint-smallint-tinyint-byteint) for consuming applications, there is a difference between an INT and NUMBER.

**Comment by ryanking** [comment]
Can you find the the query that this code generates? Running with TF_LOG=TRACE *should* print it out. Be sure to redact anything sensitive.

**Comment by sfc-gh-dsandler** [comment]
Hi @ryanking - attached is log, cleansed version of main.tf, and here is the generated DDL that ran in Snowflake.  Looking more closely, generated DDL is as expected, and what I am seeing [reflects the documented data type behavior](https://docs.snowflake.com/en/sql-reference/data-types-numeric.html).  

Generated create table DDL:


`CREATE TABLE "MYDB"."MYSCHEMA"."MYTBL" ("COLUMN1" SMALLINT, "COLUMN2" VARCHAR(100), "COLUMN3" NUMBER(10,2), "COLUMN4" FLOAT, "COLUMN5" DOUBLE) COMMENT = 'test table'`


Sorry for the false alarm, thanks for the quick response.  Closing on my end

[main.tf.txt](https://github.com/chanzuckerberg/terraform-provider-snowflake/files/5854755/main.tf.txt)
[terraform.log](https://github.com/chanzuckerberg/terraform-provider-snowflake/files/5854756/terraform.log)

**Comment by ryanking** [comment]
Thanks @sfc-gh-dsandler
