### ISSUE TITLE
Documentation for import resource snowflake_schema incorrect

### ISSUE THREAD

**Issue by ErikDolstraDPGMedia** [chanzuckerberg/terraform-provider-snowflake#434]
**Describe the bug**

The documentation for importing a schema on the Terraform Provider Registry is incorrect. On this page:
https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs/resources/schema

At the bottom it in the code example it says:
```
format is schema name | privilege | true/false for with_grant_option
terraform import snowflake_schema.example 'schemaName|USAGE|true'
```

It should be:
```
format is schema DbName | schemaName
terraform import snowflake_schema.example 'DbName|schemaName'
```

**Comment by aidan-melen** [comment]
Literally ran into this yesterday importing a schema. Can confirm doc bug and recommended fix.

**Comment by ers81239** [comment]
Came here to report this issue.  Easy fix.

**Comment by yohei1126** [comment]
#456 is a fix for this issue
