### ISSUE TITLE
Future development

### ISSUE THREAD

**Issue by sjauld** [chanzuckerberg/terraform-provider-snowflake#45]
Hi @ryanking,

Just wondering what your plans are for this repo - due to internal requirements I have now added another 8 resources on the @viostream fork plus some enhancements and bugfixes to existing resources.

Given that I have a couple of open PRs that seem to be stalled, keen to understand if you're still planning on developing/maintaining this - if so I can work out the best way to break the remaining changes back up into sensible PRs.

Cheers!

**Comment by ryanking** [comment]
@sjauld sorry for the lack of response. I have been on paternity leave for the last month, so I haven't been able to respond. I am doing to work through the open PRs this week.

**Comment by ryanking** [comment]
Also - feel free do just dump a bunch of changes in one PR, I can sort through them.

**Comment by sjauld** [comment]
Will do! And congratulations too!
