### ISSUE TITLE
Read private key from environment variable

### ISSUE THREAD

**Issue by igungor** [chanzuckerberg/terraform-provider-snowflake#471]
**Is your feature request related to a problem? Please describe.**

We're using [atlantis](https://github.com/runatlantis/atlantis) on AWS Fargate to manage our all resources, including Snowflake. Provider has private-key support but only reads from the file. It'd be best if it could read the key content directly instead of given file path. 

**Describe the solution you'd like**

A new provider attribute named `private_key` (just like `private_key_path`) which holds the private key content. Also it can be passed via environment variable `SNOWFLAKE_PRIVATE_KEY`, which enables tools like Atlantis to run on a serverless platform in a more simpler way.

**Additional context**

I'll send a PR for a more concrete approach. I understand that doing nearly the same thing with two provider attributes is not very nice, but on the other hand, it's very practical for users like us.

**Comment by dapearce** [comment]
@igungor is there a trick to how the private key needs to be provided and/or encoded a certain way? I have spent a good hour now trying to get this to work but can't get past the error `Private Key could not be parsed: Could not parse private key, key is not in PEM format`.

**Comment by thenaturalist** [comment]
Hi there, is there any update on this?

**Comment by thenaturalist** [comment]
@dapearce the above error was resolved for me when I supplied a newline delimited key string. See https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/853
