### ISSUE TITLE
Add if_not_exists parameter to object resources

### ISSUE THREAD

**Issue by franwitter** [chanzuckerberg/terraform-provider-snowflake#473]
**Is your feature request related to a problem? Please describe.**

I want to be able to share warehouse resources.  When creating new applications in snowflake I want to be able to create new warehouses if needed but if already there the can use the exisiting warehouse.  This would be helpful in DEV/QA which could have multiple working environments  but we want to share the same warehouse.

**Describe the solution you'd like**
I would like objects that have snowflake syntax [if not exists] to have that parameter added to its resource (database,schema,warehouse,etc)

**Describe alternatives you've considered**

I am trying to use terraform syntax to skip warehouse building if the warehouse exists.

**Additional context**

**Comment by ryanking** [comment]
I don't think we can support this in the provider, given how terraform works.

My best advice would be to construct your terraform code to create the warehouse only in the environments where you want by using variables, count parameters, etc.
