### ISSUE TITLE
Add resource to support "grant apply ON masking policy..."

### ISSUE THREAD

**Issue by adamrosenblit-wex** [chanzuckerberg/terraform-provider-snowflake#508]
**Is your feature request related to a problem? Please describe.**

After creating a masking policy using the `snowflake_masking_policy` resource, we would like to `GRANT APPLY ON MASKING POLICY <POLICY_NAME> TO ROLE <POLICY_ASSIGNMENT_ROLE>`.  Currently, our Terraform user/role is the only one that can assign the masking policies, since it creates them, and cannot transfer the ability to assign them for use in ELT processes.   

For reference, please see the [documentation](https://docs.snowflake.com/en/user-guide/security-column-ddm-use.html).  We are specifically interested in the `... APPLY ON MASKING POLICY ...` as it would allow us to decentralize the application of masking policies via our ELT tool, dbt.  The account level `...APPLY MASKING POLICY...` seems like it can be handled by the existing `snowflake_account_grant`, but is _not_ what we are looking for here.

**Describe the solution you'd like**

We would like a resource, eg `snowflake_masking_policy_grant`, that would allow us to run the `GRANT APPLY ON MASKING POLICY <POLICY_NAME> TO ROLE <POLICY_ASSIGNMENT_ROLE>` statement.

**Describe alternatives you've considered**

We could use a yet another third party tool, such as Flyway, to run the SQL statement, but Terraform is managing all of our other Snowflake infrastructure.  

**Additional context**

Thanks for considering this feature request!

**Comment by alldoami** [comment]
We support this now! https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/main/pkg/resources/masking_policy_grant.go

**Comment by adamrosenblit-wex** [comment]
Thanks!  Much appreciated!
