### ISSUE TITLE
Missing darwin_arm64 build

### ISSUE THREAD

**Issue by velppa** [chanzuckerberg/terraform-provider-snowflake#517]
**Provider Version**

0.24

**Terraform Version**

0.14.9

**Describe the bug**

Missing `darwin_arm64` build artefact, so `terraform init` (and installation via `download.sh`) fails on MacBook Pro M1. As per `.goreleaser.yml` build matrix, such artefact should been built.

**Expected behavior**

Artefact for `darwin_arm64` is built on releases.

**Code samples and commands**

1. Use Apple Silicon machine
2. Run `terraform apply` in a project that requires terraform-provider-snowflake plugin

**Comment by HughZurname** [comment]
I'm still getting the following on v0.25.6
```
╷
│ Error: Incompatible provider version
│
│ Provider registry.terraform.io/chanzuckerberg/snowflake v0.25.6 does not have a package available for your
│ current platform, darwin_arm64.
│
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all
│ platforms. Other versions of this provider may have different platforms supported.
╵
```
I don't really know enough about how terraform resolves releases to be able to investigate this properly, but the binary that you guys are providing for `darwin_arm64` works when I manually install it to my plugins cache.

I'm happy to try and work out why this is happening and submit a PR if someone could explain how dependences are resolved in the terraform registry?

**Comment by velppa** [comment]
@HughZurname there's no binary for darwin_arm64 in releases, if one builds it manually and puts to `plugins` it works. Probably something is wrong with release process.

<img width="1039" alt="Screenshot 2021-06-15 at 12 10 40" src="https://user-images.githubusercontent.com/480160/122035572-e1cbfb00-cdd2-11eb-8a05-c2a40f0fb889.png">

**Comment by alldoami** [comment]
Fixed in the newest release! I had to upgrade `go`
