### ISSUE TITLE
Unable to use hyphens or dashes as STRING per validation.go

### ISSUE THREAD

**Issue by tkrussy** [chanzuckerberg/terraform-provider-snowflake#526]
**Provider Version**
0.24.0

**Terraform Version**
0.13.6

**Describe the bug**
When attempting a `snowflake_role_grants` to a role that is AzureAD provisioned with a hyphen/dash, you get a plan failure for an unsupported string character.

```
Terraform v0.13.6
Configuring remote state backend...
Initializing Terraform configuration...

Error: '-' is not a valid identifier character.

on role.tf line 23, in resource "snowflake_role_grants" "platform_admin_grant":
role_name = local.snowflake_sync_role_name

Error: '-' is not a valid identifier character.

on role.tf line 23, in resource "snowflake_role_grants" "platform_admin_grant":
role_name = local.snowflake_sync_role_name
```

**Expected behavior**

I would expect the validation to allow the use of hyphens or dashes as a string
https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/881c768cc48e5717024eb54a60aa403169681ba0/pkg/snowflake/validation.go
```func isIdentifierRune(r rune) bool {
	return (r == '_' ||
		(r >= 'A' && r <= 'Z') ||
		(r >= 'a' && r <= 'z')) ||
		(r >= '0' && r <= '9')
```

**Code samples and commands**

```
locals {
  snowflake_sync_role_name = "SAMPLE-ROLE-NAME"
}

resource "snowflake_role" "platform_admin_role" {
    name = "PLATFORM_ADMIN_ROLE"
}

resource "snowflake_role_grants" "accountadmin" {
  role_name = snowflake_role.platform_admin_role.name

  roles = [
    "ACCOUNTADMIN",
  ]
}

resource "snowflake_role_grants" "platform_admin_grant" {
  role_name = local.snowflake_sync_role_name

  roles = [
    "PLATFORM_ADMIN_ROLE",
  ]
}
```

**Additional context**
Depending on usage, we may need to account for this at resource level, would need to pass validations and update unit tests.

**Comment by tkrussy** [comment]
Resolved issue internally, this does not appear to be an impactful issue moving forward based on limits imposed for naming by Snowflake

**Comment by isaacegglestone** [comment]
@tkrussy I'm running into this issue as well as our AD groups have hyphens in them.
Was there a workaround for this?
Changing our AD group names not likely going to happen due to how embedded they are currently.

No plan to fix this?

**Comment by tkrussy** [comment]
The provider was written in a SQL pattern (Grant Role to <user>;) compared to other TF patterns I had used as well. To resolve we just needed to switch which value was provided to each block. ‘role_name’ became “ACCOUNTADMIN” and role became “Hyphen-SAML-Group”

**Comment by tkrussy** [comment]
@isaacegglestone does my above reply answer or resolve your issue?

**Comment by tkrussy** [comment]
```
locals {
  ad_group_name = "AD-GROUP-NAME-WITH-HYPHENS" #scim/saml sync AD group to Snowflake
}

resource "snowflake_role" "custom_role" {
    name = "CUSTOM_ROLE_NAME"
}

#GRANT ROLE CUSTOM_ROLE_NAME TO "AD-GROUP-NAME-WITH-HYPHENS";
resource "snowflake_role_grants" "custom_role_grant" {
  role_name = snowflake_role.custom_role.name

  roles = [
    local.ad_group_name,
  ]
}

resource "snowflake_role_grants" "accountadmin" {
  role_name = "ACCOUNTADMIN"

  roles = [
    snowflake_role.custom_role.name,
  ]
  users = [
    "local_snowflake_user1",
	"local_snowflake_user2"
  ]
}

**Comment by nlawson** [comment]
@tkrussy I am running into this issue while granting a role to a user. The role seems to get created with a dash in the name but the grant fails with `Error: '-' is not a valid identifier character.`

Here is some example code that fails:

```
resource "snowflake_user" "custom_user" {
    name = "CUSTOM_USER"
}

resource "snowflake_role" "custom_role" {
    name = "CUSTOM-ROLE-NAME"
}

resource "snowflake_role_grants" "custom_role_grant" {
  role_name = snowflake_role.custom_role.name

  users = [
    snowflake_user.custom_user.name,
  ]
}
```

The workaround posted above does not work for the purposes of specifically granting a role to a user. If the role can be created but not granted, this still seems like it should be an open bug.
