### ISSUE TITLE
Role grants on the same role with two different resources leads to errors

### ISSUE THREAD

**Issue by tkandl** [chanzuckerberg/terraform-provider-snowflake#530]
**Provider Version**
0.25.0

**Terraform Version**
0.15.1

**Describe the bug**
I have set up two resources to grant a role to another role and to a user:
```
resource snowflake_role_grants sysadmin_grant {
  role_name = "DS_EXTERNAL_ADMIN"
  roles = ["SYSADMIN"]
}

resource snowflake_role_grants service_user_grant {
  role_name = "DS_EXTERNAL_ADMIN"
  users = ["DS_EXTERNAL_SERVICE_USER"]
}
```

If I apply the changes everything works as expected. When I run the plan again, Terraform wants to apply changes although nothing has changed:
```
  ~ resource "snowflake_role_grants" "sysadmin_grant" {
        id        = "DS_EXTERNAL_ADMIN"
      ~ users     = [
          - "DS_EXTERNAL_SERVICE_USER",
        ]
        # (2 unchanged attributes hidden)
    }

  ~ resource "snowflake_role_grants" "service_user_grant" {
        id        = "DS_EXTERNAL_ADMIN"
      ~ roles     = [
          - "SYSADMIN",
        ]
        # (2 unchanged attributes hidden)
    }
```
It seems the two resources have been interchanged:
The sysadmin_grant sets the user and the service_user_grant the role.

Could the same id be the problem?
I tried to set the id manually but got the error that the key is invalid.

**Comment by alldoami** [comment]
If the `role_name` is the same, you need to put all of the `roles` and `users` in the same resource.
