### ISSUE TITLE
Stored procedures and functions

### ISSUE THREAD

**Issue by funes79** [chanzuckerberg/terraform-provider-snowflake#532]
**Is your feature request related to a problem? Please describe.**

Is there a plan to support stored procedures and functions as resources? I see the grant for function is already here, but I cannot find function as a resource.

**Describe the solution you'd like**

Two new resources: stored procedure and user defined function.

**Describe alternatives you've considered**

.

**Additional context**

.

**Comment by fonsecalink** [comment]
Is there any work around to deploy stored procedures?

**Comment by approximately-birds** [comment]
is there a plan to do this? is there a workaround?

**Comment by funes79** [comment]
If nobody is working on it, I can take it, will create a PR for stored procedures..

**Comment by funes79** [comment]
PR created https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/619
