### ISSUE TITLE
USE WAREHOUSE fails if not quoted

### ISSUE THREAD

**Issue by mariamtm** [chanzuckerberg/terraform-provider-snowflake#544]
Provider Version v0.25.1
Terraform Version Terraform v0.14.8

After creating a warehouse as indicated in the documentation:

```
resource "snowflake_warehouse" "elt" {
    name = "test_elt_l0"
    warehouse = "xsmall"
    auto_suspend = 60
}
```

I can not use this created warehouse unless the name is specified in quotes:

```
USE WAREHOUSE "test_elt_l0"
```

If I put it without quotes I get the following result:

`SQL compilation error: Object does not exist, or operation cannot be performed.`

Is there a way to create the warehouses without quotes just like in the snowflake console?

**Comment by camaya** [comment]
Hi @mariamtm 

I was experiencing a similar issue with the quotation and it turns out it's a Snowflake thing rather than something from this provider. Check this discussion to see the details: https://github.com/chanzuckerberg/terraform-provider-snowflake/discussions/558

Cheers
