### ISSUE TITLE
Resource snowflake_role_grants doesn't accept roles with dots: '.' is not a valid identifier character

### ISSUE THREAD

**Issue by MPierre9** [chanzuckerberg/terraform-provider-snowflake#578]
**Provider Version**

0.25.6

**Terraform Version**

1.0.0

**Describe the bug**

When using the 'snowflake_role_grants' resource, if the role_name is something like ".my.roleName"

Terraform throw error: Error: '.' is not a valid identifier character.

**Expected behavior**

The role grant is created for roles with dots in them

**Code samples and commands**

```
resource "snowflake_role_grants" "grants" {

  role_name = ".GRP.ROLENAME"

  roles = ["ACCOUNTADMIN"]
}
```

**Comment by alldoami** [comment]
Convention is to use `_` and not `.`. Can you use that instead?

**Comment by MPierre9** [comment]
Thanks for the comment @alldoami 

With how we have our Snowflake setup, the roles are being synced from our Azure active directory groups which mostly have dots in them. For example, these show in Snowflake like: 
![image](https://user-images.githubusercontent.com/27080760/122458704-1b8d3500-cf7e-11eb-8993-53ab40672eb3.png)

Is there a way to escape the dot or have it interpreted differently?

**Comment by alldoami** [comment]
How are you syncing your Azure active directory groups with Snowflake? Is there a way to put in an intermediate step?

**Comment by MPierre9** [comment]
We're syncing them using the Azure AD provisioner which does a 1:1 map. That's a good suggestion though and will likely solve the problem. In Azure AD we can customize the the attribute mapping to change "." to "_" as an intermediate step.

I'll drop a link and example in case someone else has this issue:

[Azure AD: replace-characters-using-a-regular-expression](https://docs.microsoft.com/en-us/azure/active-directory/app-provisioning/functions-for-customizing-application-data#replace-characters-using-a-regular-expression)

![image](https://user-images.githubusercontent.com/27080760/123155066-a1edbf00-d435-11eb-8d7b-da25a5b4241d.png)

Thanks @alldoami !
