### ISSUE TITLE
snowflake_schema_grant rejects valid privileges

### ISSUE THREAD

**Issue by jrobison-sb** [chanzuckerberg/terraform-provider-snowflake#579]
**Provider Version**

```
+ provider registry.terraform.io/chanzuckerberg/snowflake v0.25.4
```

**Terraform Version**

```
Terraform v0.13.5
```

**Describe the bug**

`CREATE DIRECTORY TABLE` and `CREATE ROW ACCESS POLICY` are both valid schema privileges, but the provider doesn't allow them to be used with the `snowflake_schema_grant` resource.

```
Error: expected privilege to be one of [CREATE FILE FORMAT CREATE FUNCTION CREATE PROCEDURE CREATE MATERIALIZED VIEW OWNERSHIP CREATE VIEW MONITOR CREATE TASK CREATE TABLE CREATE PIPE CREATE STREAM CREATE SEQUENCE CREATE EXTERNAL TABLE CREATE TEMPORARY TABLE MODIFY USAGE CREATE MASKING POLICY ADD SEARCH OPTIMIZATION CREATE STAGE], got CREATE DIRECTORY TABLE
```

(And the same error with `CREATE ROW ACCESS POLICY`.)

**Expected behavior**

Those privileges should be allowed.

**Code samples and commands**

```
resource "snowflake_schema_grant" "public_schema" {
  for_each = toset([
    "CREATE DIRECTORY TABLE",
    "ADD SEARCH OPTIMIZATION",
    "CREATE FILE FORMAT",
    "CREATE EXTERNAL TABLE",
    "CREATE FUNCTION",
    "CREATE MASKING POLICY",
    "CREATE PIPE",
    "CREATE MATERIALIZED VIEW",
    "CREATE ROW ACCESS POLICY",
    "CREATE PROCEDURE",
    "CREATE SEQUENCE",
    "CREATE STAGE",
    "CREATE STREAM",
    "CREATE TABLE",
    "CREATE TEMPORARY TABLE",
    "CREATE TASK",
    "CREATE VIEW",
    "MODIFY",
    "MONITOR",
    "USAGE"
  ])
  database_name = snowflake_database.foo[0].name
  schema_name   = "PUBLIC"
  privilege     = each.key
  roles         = [snowflake_role.role[0].name]
  with_grant_option = true
}
```

**Comment by dtger** [comment]
@jrobison-sb Curious what create directory table grant does, I cannot seem to find any documentation on it. Otherwise I concur, the following don't work for me:
```
ADD SEARCH OPTIMIZATION
CREATE TEMPORARY TABLE
```

**Comment by jrobison-sb** [comment]
@dtger I couldn't find any documentation on it either, so I'm not really sure what it does. A coworker found a list of privileges in the Snowflake UI and pasted a bunch of them to me to be added by Terraform. That's really the only way that I know CREATE DIRECTORY TABLE to be a valid privilege.

![image](https://user-images.githubusercontent.com/39737211/122449160-8d13b600-cf73-11eb-8e69-d1d11867bfc4.png)

CREATE ROW ACCESS POLICY produces the same error and that one [is documented](https://docs.snowflake.com/en/sql-reference/sql/create-row-access-policy.html).

**Comment by alldoami** [comment]
Hmm I cannot find `CREATE DIRECTORY TABLE` either... Since it's not well documented, I'll only add the `CREATE ROW ACCESS POLICY` for now.
