### ISSUE TITLE
Terraform modules snowflake-XXX-grant-all should not have OWNERSHIP privileges 

### ISSUE THREAD

**Issue by wconti1017** [chanzuckerberg/terraform-provider-snowflake#593]
All the terraform modules have in their privileges list the OWNERSHIP role, for example on the snowflake-warehouse-grant-all module :

"privileges": [
  "MODIFY",
  "MONITOR",
  "OPERATE",
  "OWNERSHIP",
  "USAGE"
]
This is incorrect, because the actual result of the Snowflake command GRANT ALL ON WAREHOUSE <wh> TO ROLE <role> will give the following privileges : MODIFY, MONITOR, OPERATE and USAGE.

**Comment by alldoami** [comment]
What version of the provider are you using? We have gotten rid of the `ALL` grant because it was too difficult to maintain.

**Comment by alldoami** [comment]
https://github.com/chanzuckerberg/terraform-provider-snowflake/discussions/318

**Comment by wconti1017** [comment]
@alldoami I've opened an issue on the [cztack repository](https://github.com/chanzuckerberg/cztack/issues/317), as the bug is not on the terraform provider. I am closing this one.
