### ISSUE TITLE
Support for `ROW ACCESS POLICY`

### ISSUE THREAD

**Issue by LouisAmon** [chanzuckerberg/terraform-provider-snowflake#615]
**Describe the solution you'd like**

Support for for the `ROW ACCESS POLICY` resource

**Additional context**

https://docs.snowflake.com/en/sql-reference/sql/create-row-access-policy.html

https://docs.snowflake.com/en/user-guide/security-row-using.html

Data access management is one of the things that should definitely be done via IaC :)

**Comment by ChrisIsidora** [comment]
@LouisAmon  I also needs this, I will try to work on it and open a PR this week, it might be tricky with the multi arguments bit.
