### ISSUE TITLE
Support all global privileges on account grants

### ISSUE THREAD

**Issue by nbob31** [chanzuckerberg/terraform-provider-snowflake#643]
**Is your feature request related to a problem? Please describe.**

When creating account grants currently only the following are supported. 
```
"APPLY MASKING POLICY", "CREATE SHARE", "IMPORT SHARE", "MONITOR EXECUTION", 
"CREATE USER", "CREATE WAREHOUSE", "CREATE DATABASE", "CREATE INTEGRATION", 
"MANAGE GRANTS", "MONITOR USAGE", "EXECUTE TASK", "CREATE ROLE"
```

**Describe the solution you'd like**

Add support for all global privileges on account grants described in the snowflake access control privileges documentation](https://docs.snowflake.com/en/user-guide/security-access-control-privileges.html#global-privileges)

```
APPLY MASKING POLICY
APPLY ROW ACCESS POLICY
APPLY TAG
ATTACH POLICY
CREATE DATA EXCHANGE LISTING
CREATE NETWORK POLICY
OVERRIDE SHARE RESTRICTIONS
CREATE ACCOUNT
```
**Describe alternatives you've considered**

**Additional context**

**Comment by nbob31** [comment]
https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/635 should close this.

**Comment by ChrisIsidora** [comment]
@nbob31 #635 is merged can you close this issue
