### ISSUE TITLE
checksum issue for mac os

### ISSUE THREAD

**Issue by dot-run-code** [chanzuckerberg/terraform-provider-snowflake#662]
**Provider Version** 0.20.0

 0.20.0.

**Terraform Version**

0.14.6

**Describe the bug
When running it on mac os-it is unable to load the provider.It is complaining the checksum mismatch.

Terraform failed to fetch the requested providers for darwin_amd64 in order to
calculate their checksums: some providers could not be installed:
- registry.terraform.io/chanzuckerberg/snowflake: archive has incorrect
checksum zh:29c74bb922739cddff0d5d2ade723cba4750ee60fadd36b43fa0d53a9e68df35
(expected
zh:e59b5cd10a6cc7d3d46fc05c4c31e03477b62f5f80cd4921fc8074327743f3a1).

**Expected behavior**

Should be successfully install terraform provider.
**Code samples and commands**
./terraform providers lock -platform=darwin_amd64

terraform {
  required_providers {
    snowflake = {
      source = "chanzuckerberg/snowflake"
      version = "0.20.0"
    }
  }
}

**Comment by erickpearson** [comment]
This is happening on latest version of the project, I've tried many different versions and its the same error. This is affecting all of our deployments. Any update on this issue?

**Comment by tonybadguy** [comment]
I'm having the same issue as well

**Comment by dot-run-code** [comment]
Not an issue.
