### ISSUE TITLE
Cannot import database

### ISSUE THREAD

**Issue by tolik93** [chanzuckerberg/terraform-provider-snowflake#668]
**Provider Version**
  version     = "0.25.18"

**Terraform Version**

Terraform v1.0.5

**Describe the bug**

I tried to import the existing database into terraform but it fails. 
```Error: Invalid provider configuration
│ 
│   on /home/novosolova/ims-go/terraform-config-snowflake-development/providers.tf line 1:
│    1: provider "snowflake" {
│ 
│ The configuration for provider["registry.terraform.io/chanzuckerberg/snowflake"].accountadmin depends on values that cannot be determined until apply.
```

**Expected behavior**

**Code samples and commands**

```terraform
resource "snowflake_database" "this" {

  for_each = toset([
    "MY_DB",
  ])

  name                        = each.value
  data_retention_time_in_days = 7
}

```

**Additional context**

**Comment by tolik93** [comment]
Pulling the state from the remote backend and importing resources locally is a workaround.

**Comment by Bryan-Meier** [comment]
@tolik93, I am fairly new to Terraform but I have the same question as was prompted here. I would like to import a list of databases without having to create a resource for each database and import them one by one. You mentioned pulling the state from the remote backend and importing resources locally. Could you give me an example or point me to what you are referring to? If you found a way to import a list of existing databases without having to create resource and do an import for each database, I would be interested to learn how you accomplished that. Thank you!

**Comment by tolik93** [comment]
Hey @Bryan-Meier, 
terraform cli contains some commands to [pull](https://www.terraform.io/docs/cli/commands/state/pull.html)/[push](https://www.terraform.io/docs/cli/commands/state/push.html) the terraform state.

In my case I have to pull the current remote state, that is referenced in my terraform backend configuration:
```hcl
terraform {
  backend "remote" {
    hostname     = "app.terraform.io"
    organization = "***"
    workspaces {
      name = "***"
    }
  }
}
```

1. `terraform state pull`
2. comment out your terraform backend configuration and reinit using `terraform init`
3.  Import the resources using `terraform import snowflake_database.name db-name`
4. remove comment blocks from your terraform backend configuration and reinit using `terraform init`
5.  `terrraform state push`

In some steps terraform will recognize state changes and prompt you for changes.

I hope it can be helpful for you!

**Comment by Bryan-Meier** [comment]
Thanks for the response @tolik93! I actually implemented a similar pattern to what you had at the beginning. We are using Terraform Cloud which uses the "cloud" block instead of "backend". It actually works pretty well. You still have to do the import from your local but it's importing the resource (aka db, schema, warehouse, etc.) into the state file in the cloud since a state file doesn't exist locally. I will say though, that if you are importing a lot of resources it's a slow process due to the overhead required to communicate with the cloud as it pertains to the state file.

Thanks again for the response!
