### ISSUE TITLE
snowflake_stage_grant is replaced every time I apply

### ISSUE THREAD

**Issue by dperrett** [chanzuckerberg/terraform-provider-snowflake#669]
**Provider Version**

v0.25.18

**Terraform Version**

v1.0.2

**Describe the bug**

Edit: my initial assumption that `shares` was causing this is wrong - the culprit is `roles`.

~~My `snowflake_stage_grant` is replaced every time I `apply`, because `shares` has changed from `null` to `[]` behind the scenes (regardless of whether I set it to (`null` to `[]`).~~

My `snowflake_stage_grant` is marked for replacement every time I `plan`, if there are two `roles` specified. If I specify only one role (it doesn't matter which one), it works as expected on the second `apply`.

**Expected behavior**

The `snowflake_stage_grant` should not be replaced every time I `apply`.

**Code samples and commands**

I have the following grant set up:

```
resource "snowflake_stage_grant" "snowpipe_test" {
  database_name = snowflake_database.data.name
  schema_name   = snowflake_schema.snowpipe_test.name
  roles         = [snowflake_role.snowpipe_test.name, "TERRAFORM"]
  privilege     = "OWNERSHIP"
  stage_name    = snowflake_stage.snowpipe_test.name
}
```

Every time I `plan` this, I get the following result:

```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # module.studio_etl.snowflake_stage_grant.snowpipe_test has been changed
  ~ resource "snowflake_stage_grant" "snowpipe_test" {
        id                = "DATA_DEVELOPMENT|SNOWPIPE_TEST|SNOWPIPE_TEST_STAGE_DEVELOPMENT|OWNERSHIP|false"
      ~ roles             = [
          - "SNOWPIPE_TEST_DEVELOPMENT",
            # (1 unchanged element hidden)
        ]
      + shares            = []
        # (6 unchanged attributes hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to
these changes.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # module.studio_etl.snowflake_stage_grant.snowpipe_test must be replaced
-/+ resource "snowflake_stage_grant" "snowpipe_test" {
      ~ id                = "DATA_DEVELOPMENT|SNOWPIPE_TEST|SNOWPIPE_TEST_STAGE_DEVELOPMENT|OWNERSHIP|false" -> (known after apply)
      ~ roles             = [ # forces replacement
          + "SNOWPIPE_TEST_DEVELOPMENT",
            # (1 unchanged element hidden)
        ]
      - shares            = [] -> null
        # (6 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

Do you want to perform these actions?
```

~~Basically (from my understanding) Terraform thinks that `shares` is `[]` every time it refreshes, but the provider is setting it to `null`  (even if I set it to `[]`), and the next time I plan it replaces the stage again.~~

~~I have tried adding a share just to have something to put in the array, but it started a bit of a rabbit hole that was looking quite complicated for something that I don't actually need.~~

If I use `roles = [snowflake_role.snowpipe_test.name, "TERRAFORM"]`, I get this issue. It doesn't matter which order I put the two roles in, and it doesn't matter if I use an explicit string instead of `snowflake_role.snowpipe_test.name` - the issue still occurs. If I use `roles = [snowflake_role.snowpipe_test.name]` or `roles = ["TERRAFORM"]`, everything works as expected.

I've added `ignore_changes = [roles]` for now, but it would be really nice to figure this out. Any suggestions or ideas here would be much appreciated!

**Additional context**

N/A

**Comment by dperrett** [comment]
Maybe `OWNERSHIP` can't be granted to two roles? 🤔

**Comment by alldoami** [comment]
This comment https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/669#issuecomment-913336321 is correct.
