### ISSUE TITLE
Warehouse always shows a change to the statement timeout even when no changes have been made

### ISSUE THREAD

**Issue by bburner** [chanzuckerberg/terraform-provider-snowflake#710]
**Provider Version**

0.25.19

**Terraform Version**

1.0.8

**Describe the bug**

Resource blocks for snowflake_warehouse with statement_timeout_in_seconds set apply the timeout to snowflake correctly, but when re-running terraform plan with no changes, terraform sees the statement_timeout_in_seconds as a change. I verified that this bug was introduced with provider version 0.25.11. When downgrading to version 0.25.10 and below, I see the expected behavior. For versions > 0.25.10 terraform displays this bug.

**Expected behavior**

running terraform plan when no changes are made to a warehouse should display "no changes"

**Code samples and commands**

below is a complete example to reproduce this issue. run terraform apply. verify the warehouse is created with a timeout of 600 as expected. run terraform plan again with no changes. terraform will show 1 change: 

statement_timeout_in_seconds        = 0 -> 600

```terraform {
  required_providers {
    snowflake = {
      source  = "chanzuckerberg/snowflake"
      version = "0.25.19"
    }
  }
}

provider "snowflake" {
  alias = "sys_admin"
  role  = "SYSADMIN"
}

provider "snowflake" {
  alias = "security_admin"
  role  = "SECURITYADMIN"
}

provider "snowflake" {
  alias = "account_admin"
  role  = "ACCOUNTADMIN"
}

resource "snowflake_warehouse" "git_example" {
  provider              = snowflake.sys_admin
  name                  = "git_example"
  comment               = "an example illustrating a bug"
  warehouse_size        = "small"
  max_cluster_count     = 2
  min_cluster_count     = 1
  initially_suspended   = true
  auto_resume           = true
  auto_suspend          = 60
  scaling_policy        = "ECONOMY"
  statement_timeout_in_seconds = 600
}
```

**Additional context**

**Comment by clettieri** [comment]
@bburner any resolution?  We are seeing this same issue since upgrading the provider.
