### ISSUE TITLE
Support for table_grant and/or future table grants

### ISSUE THREAD

**Issue by pwnage101** [chanzuckerberg/terraform-provider-snowflake#76]
We provision schemas via terraform, then populate tables in them via some other automation.  However, there's no way for other users to view tables in this pre-populated schema unless I run:

```sql
GRANT SELECT ON ALL TABLES IN SCHEMA <schema> TO ...
```

Currently, we supplement our terraform with a carefully curated list of such statements, but I would much rather we just managed everything in terraform, including table grants.

**Comment by pwnage101** [comment]
My reservation to modifying the existing view_grant was that it has a view_name parameter which would be irrelevant to future grants, so I would have to change it from required to optional.

**Comment by pwnage101** [comment]
But if that were the case, then it could look like:

```tf
resource "snowflake_view_grant" {
  privilege = "SELECT"
  future_views = true
  database_name = "PROD"
  schema_name = "MYSCHEMA"
  object_type = "TABLE"
  roles = [ "MYSCHEMA_READER" ]
  # setting view_name is invalid when future_views = true
  # setting shares is invalid when future_views = true
}
```

Setting view_name becomes required when future_views = false, and shares becomes valid but optional.

**Comment by ryanking** [comment]
@pwnage101 I think that makes sense and is a simpler api. Let's see if it works?
