### ISSUE TITLE
Cannot download providers with terraform init

### ISSUE THREAD

**Issue by rtacconi** [chanzuckerberg/terraform-provider-snowflake#784]
When I run terraform init, it is does to download the provider:

│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider
│ chanzuckerberg/snowflake: no available releases match the given constraints
│ 0.23.2, 0.25.16

Is there a problem with the registry?

**Comment by pen-sadiq** [comment]
Hi @rtacconi, did you find a solution? I'm getting the same with 0.25.32
