### ISSUE TITLE
Error on snowflake_database_grant granting IMPORTED privilige

### ISSUE THREAD

**Issue by LukasSandm** [chanzuckerberg/terraform-provider-snowflake#790]
**Provider Version**

chanzuckerberg/snowflake v0.25.30

**Terraform Version**

1.0.5

**Describe the bug**

Getting an error on a snowflake_database_grant.

╷
│ Error: expected privilege to be one of [OWNERSHIP REFERENCE_USAGE USAGE CREATE SCHEMA IMPORTED PRIVILEGES MODIFY MONITOR], got IMPORTED
│ 
│   with snowflake_database_grant.database_snowflake_grant_imported,
│   on account_ privileges.tf line 12, in resource "snowflake_database_grant" "database_snowflake_grant_imported":
│   12:   privilege     = "IMPORTED"
│ 
╵
ERRO[0005] 1 error occurred:
	* exit status 1

**Expected behavior**

Granting IMPORTED privilige on database to SYSADMIN role following this doc:
https://docs.snowflake.com/en/sql-reference/account-usage.html

**Code samples and commands**

resource "snowflake_database_grant" "database_snowflake_grant_imported" {
  database_name = "SNOWFLAKE"
  privilege     = "IMPORTED"
  roles         = ["SYSADMIN"]
  depends_on    = [snowflake_role.role]
}

**Comment by christopherridley** [comment]
I think you have to use `privilege = "IMPORTED PRIVILEGES"`.

**Comment by LukasSandm** [comment]
> 

Thanks @christopherridley , that worked
