### ISSUE TITLE
Change of AWS SNS Topic for Snowpipe should require the recreation of the pipe

### ISSUE THREAD

**Issue by rhadoopo** [chanzuckerberg/terraform-provider-snowflake#816]
**Is your feature request related to a problem? Please describe.**

Currently, when the underlying SNS topic for a Snowpipe is being changed, the provider mentions that something needs to be changed for the Snowpipe, but nothing happens. 

**Describe the solution you'd like**

Since Snowflake does not allow altering the SNS topic for a Snowpipe, the provider should destroy and recreate the Snowpipe in case 
the SNS topic was changed.

This would require a change here: https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/main/pkg/resources/pipe.go#L61

```
"aws_sns_topic_arn": {
    Type:        schema.TypeString,
    Optional:    true,
    ForceNew:    true,
    Description: "Specifies the Amazon Resource Name (ARN) for the SNS topic for your S3 bucket.",
}
```

**Comment by chris922** [comment]
I added a PR for this.. maybe we should even look at other properties and add `ForceNew` to them (like `integration`)
