### ISSUE TITLE
Snowflake role with dash (`-`) in its name can be created but not granted

### ISSUE THREAD

**Issue by nlawson** [chanzuckerberg/terraform-provider-snowflake#846]
**Provider Version**

0.25.36

**Terraform Version**

0.14.5

**Describe the bug**

When using terraform to grant a role to a user, the role (`snowflake_role`) can be created with a dash in the name, but a grant to a role (`snowflake_role_grants`) with a dash in its name fails with `Error: '-' is not a valid identifier character.`

**Expected behavior**

A grant should be able to be created for any roles that have been successfully created with `snowflake_role`. 

**Code samples and commands**

```
resource "snowflake_user" "custom_user" {
    name = "CUSTOM_USER"
}

resource "snowflake_role" "custom_role" {
    name = "CUSTOM-ROLE-NAME"
}

resource "snowflake_role_grants" "custom_role_grant" {
  role_name = snowflake_role.custom_role.name

  users = [
    snowflake_user.custom_user.name,
  ]
}
```

In the above example, the `snowflake_role.custom_role` resource can be created (if the `custom_role_grant` resource is removed), but the `custom_role_grant` fails with:

```
Error: '-' is not a valid identifier character.

on users.tf line 10, in resource "snowflake_role_grants" "custom_role_grant":
10:   role_name = snowflake_role.custom_role.name
```

**Additional context**

A similar has been opened and closed with a "workaround" in https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/526

The suggested workaround does not work for the purposes of specifically granting a role to a user. If the role can be created but not granted, this seems like it should be an open issue.

**Comment by wli-brex** [comment]
Verified that this issue is fixed using the latest v0.29.0
