### ISSUE TITLE
Publish release 0.26.3 to the provider registry

### ISSUE THREAD

**Issue by BoAustin** [chanzuckerberg/terraform-provider-snowflake#857]
Is it possible to get version 0.26.3 published to the terraform provider registry?

We are hoping to take advantage of the new replication support.

**Comment by jacobrheath** [comment]
Thanks for calling this out. @alldoami worked on this on Friday and it appears to be releasing properly now. I'll close this for now, but let us know if you have issues using the latest provider version.
