### ISSUE TITLE
Vulnerability issue in AWS S3 Crypto SDK for golang

### ISSUE THREAD

**Issue by ericpar** [chanzuckerberg/terraform-provider-snowflake#866]
I believe there is a vulnerability issue with the AWS S3 Crypto SDK for golang.
Is it possible to address this issue ?

References:
https://github.com/advisories/GHSA-76wf-9vgp-pj7w
https://github.com/google/security-research/security/advisories/GHSA-76wf-9vgp-pj7w

**Comment by jacobrheath** [comment]
Based on the reading of https://github.com/advisories/GHSA-76wf-9vgp-pj7w and https://github.com/google/security-research/security/advisories/GHSA-76wf-9vgp-pj7w, this sounds resolved by AWS?

> The issue has been fixed server-side by AWS as of Aug 5th, by blocking the related metadata field. No S3 objects are affected anymore.

> The issue has been fixed server-side by AWS as of Aug 5th, by blocking the related metadata field. No S3 objects are affected anymore.

In any case, we are updating our SDK versions this release. If there is more information about how those issues affect the provider, please let us know so we can investigate further.
