### ISSUE TITLE
0.26.* Releases not showing up on the terraform registry

### ISSUE THREAD

**Issue by sjezewski** [chanzuckerberg/terraform-provider-snowflake#873]
Specifying the following : 

```
terraform {
  required_version = "~> 1.0"

  required_providers {
    snowflake = {
      source  = "chanzuckerberg/snowflake"
      version = "~> 0.26.0"
    }
  }
}
```

Fails during `terraform init -upgrade` with the message:

```
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider chanzuckerberg/snowflake: no available releases match the given constraints ~>
│ 0.25.0, ~> 0.26.0
```

- [It looks like the last release on the terraform registry is 0.25.36](https://registry.terraform.io/providers/chanzuckerberg/snowflake/0.25.36)
- [While the latest release here on github is 0.26.3](https://github.com/chanzuckerberg/terraform-provider-snowflake/releases)

Is this by design? Is there a process that releases to the terraform registry, and the delay in releases is purposeful?

I'm waiting for [this bugfix](https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/824) to land. 

For now I can fallback to downloading the release / using a local path install with terraform.

**Comment by thenaturalist** [comment]
There is another open issue here since two weeks: https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/857

**Comment by sjezewski** [comment]
It'd be awesome to get this released properly. But in case others are hurting for the bugfixes, here's a snippet on how to get the binary installed / working locally:

```
curl -L https://github.com/chanzuckerberg/terraform-provider-snowflake/releases/download/v0.26.3/terraform-provider-snowflake_0.26.3_darwin_amd64.zip --output terraform-provider-snowflake_0.26.3_darwin_amd64.zip
unzip terraform-provider-snowflake_0.26.3_darwin_amd64.zip
export plugin_path=/usr/local/lib/terraform/registry.terraform.io/chanzuckerberg/snowflake/0.26.3/darwin_amd64
mkdir -p $plugin_path
mv terraform-provider-snowflake_v0.26.3 $plugin_path
```

Then add to `~/.terraformrc`:
```
provider_installation {
  direct {
    exclude = ["chanzuckerberg/snowflake"]
  }
  filesystem_mirror {
    path = "/usr/local/lib/terraform"
    include = ["chanzuckerberg/snowflake"]
  }
}
```

Then do a `terraform init -upgrade`

Note - I saw a bunch of `Error: 5 or 6 fields allowed` errors when looking at the plan. Just blowing away those objects w a `terraform rm state xxx` was sufficient for my use case (since I wanted them recreated).

**Comment by yohei1126** [comment]
@alldoami hey, the recent releases have not been pushed to the registry. would you check it?

**Comment by yohei1126** [comment]
@alldoami the latest release version on Github is 0.27.0 but 0.25.36 on terraform registry.
https://github.com/chanzuckerberg/terraform-provider-snowflake/releases
https://registry.terraform.io/providers/chanzuckerberg/snowflake/0.25.36

**Comment by yohei1126** [comment]
@alldoami Would you check the release bot? This was failed https://github.com/chanzuckerberg/terraform-provider-snowflake/runs/5397870219?check_suite_focus=true

**Comment by yohei1126** [comment]
@alldoami @edulop91 Would you check the release bot? This was failed https://github.com/chanzuckerberg/terraform-provider-snowflake/runs/5397870219?check_suite_focus=true

**Comment by skp33** [comment]
You can use following script for your automation.

Create file `<project path>/setup_latest_chanzuckerberg_snowflake.sh`

```
#!/bin/bash

dir=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )

version=0.26.3

curl -L https://github.com/chanzuckerberg/terraform-provider-snowflake/releases/download/v${version}/terraform-provider-snowflake_${version}_darwin_amd64.zip --output /tmp/terraform-provider-snowflake_${version}_darwin_amd64.zip
unzip -o /tmp/terraform-provider-snowflake_${version}_darwin_amd64.zip -d /tmp
export plugin_path=$dir/terraform/registry.terraform.io/chanzuckerberg/snowflake/${version}/darwin_amd64
mkdir -p $plugin_path
mv /tmp/terraform-provider-snowflake_v${version} $plugin_path

provider_path=$dir/terraform

cat << EOF > ~/.terraformrc
provider_installation {
  direct {
    exclude = ["chanzuckerberg/snowflake"]
  }
  filesystem_mirror {
    path = "$provider_path"
    include = ["chanzuckerberg/snowflake"]
  }
}
EOF

```
Then run `bash setup_latest_chanzuckerberg_snowflake.sh`

**Comment by yohei1126** [comment]
https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/893

**Comment by yohei1126** [comment]
@alldoami @edulop91  `v0.28.3` has not been released in Terraform registry. `0.25.36` is still the latest in registry. Wou

**Comment by ChrisIsidora** [comment]
Any updates on this?

**Comment by yohei1126** [comment]
fixed https://registry.terraform.io/providers/chanzuckerberg/snowflake/0.28.6

**Comment by jacobrheath** [comment]
Thanks for calling this out, everyone. @alldoami worked on this on Friday and it appears to be releasing properly now. I'll close this for now, but let us know if you have issues using the latest provider version.

**Comment by ChrisIsidora** [comment]
@jacobrheath only issue I have now is that #824 is breaking existing terraform deployments due to the change of resource id's
