### ISSUE TITLE
Support for Power BI integrations

### ISSUE THREAD

**Issue by ericpar** [chanzuckerberg/terraform-provider-snowflake#874]
**Is your feature request related to a problem? Please describe.**

The support for PowerBI integrations is not present at the moment of writing this issue.

**Describe the solution you'd like**

Having a resource that would match the requirements for provisioning a PowerBI security integration in Snowflake.

**Describe alternatives you've considered**

The basic OAUTH integration is not suitable to be used as a replacement for Power BI security integrations (external OAUTH authentication).

**Additional context**

The official Snowflake documentation on how to set a security integration for Power BI: https://docs.snowflake.com/en/user-guide/oauth-powerbi.html#creating-a-power-bi-security-integration

**Comment by ChrisIsidora** [comment]
This can be closed @ericpar

**Comment by ericpar** [comment]
Closing this issue as the new feature has been developed (see #879 )
