### ISSUE TITLE
snowflake_masking_policy resource cannot create policy mask that calls User Defined Functions

### ISSUE THREAD

**Issue by internetofjames** [chanzuckerberg/terraform-provider-snowflake#884]
**Provider Version**

0.25.36 (latest release as of 2022/03/03 on https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest)

**Terraform Version**

Terraform v1.0.2

**Describe the bug**

The `snowflake_masking_policy` resource cannot create a masking policy when a UDF (User Defined Function) is included in the masking expression. `terraform apply` fails with the error `Error: error creating masking policy SOME_MASKING_POLICY: 002140 (42601): SQL compilation error: Unknown function SOME_UDF` even though the UDF has been successfully created by the same `terraform apply` command.

**Expected behavior**

A Snowflake masking policy should be successfully created. 

**Code samples and commands**

Here's a simple example that I cannot get to work with the provider, but can execute via SQL commands in the Snowflake UI:

```terraform
resource "snowflake_function" "function_1" {
  name     = "SOME_UDF_MASK"
  database = "SOME_DATABASE"
  schema   = "SOME_SCHEMA"
  arguments {
    name = "VAL"
    type = "VARIANT"
  }
  return_type         = "VARIANT"
  language            = "javascript"
  null_input_behavior = "RETURNS NULL ON NULL INPUT"
  statement = <<-EOT
    if ("privateInfo" in VAL) {
      VAL["privateInfo"] = "*****";
    }
    return VAL;
  EOT
}

resource "snowflake_masking_policy" "masking_policy_1" {
  name               = "SOME_MASKING_POLICY"
  database           = "SOME_DATABASE"
  schema             = "SOME_SCHEMA"
  value_data_type    = "VARIANT"
  return_data_type   = "VARIANT"
  masking_expression = "${snowflake_function.function_1.name}(val)"
}
```

Running `terraform apply`:

```bash
terraform apply
2022/03/03 09:10:06 [DEBUG] POST https://some-terraform-state-url/lock
Acquiring state lock. This may take a few moments...
2022/03/03 09:10:07 [DEBUG] GET https://some-terraform-state-url

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
  + create

Terraform will perform the following actions:

  # snowflake_function.function_1 will be created
  + resource "snowflake_function" "function_1" {
      + comment             = "user-defined function"
      + database            = "SOME_DATABASE"
      + id                  = (known after apply)
      + language            = "javascript"
      + name                = "SOME_UDF_MASK"
      + null_input_behavior = "RETURNS NULL ON NULL INPUT"
      + return_behavior     = "VOLATILE"
      + return_type         = "VARIANT"
      + schema              = "SOME_SCHEMA"
      + statement           = <<-EOT
            if ("privateInfo" in VAL) {
              VAL["privateInfo"] = "*****";
            }
            return VAL;
        EOT

      + arguments {
          + name = "VAL"
          + type = "VARIANT"
        }
    }

  # snowflake_masking_policy.masking_policy_1 will be created
  + resource "snowflake_masking_policy" "masking_policy_1" {
      + database           = "SOME_DATABASE"
      + id                 = (known after apply)
      + masking_expression = "SOME_UDF_MASK(val)"
      + name               = "SOME_MASKING_POLICY"
      + return_data_type   = "VARIANT"
      + schema             = "SOME_SCHEMA"
      + value_data_type    = "VARIANT"
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

snowflake_function.function_1: Creating...
snowflake_function.function_1: Creation complete after 2s [id=SOME_DATABASE|SOME_SCHEMA|SOME_UDF_MASK|VARIANT]
snowflake_masking_policy.masking_policy_1: Creating...
2022/03/03 09:10:29 [DEBUG] POST https://some-terraform-state-url?ID=some-UUID
╷
│ Error: error creating masking policy SOME_MASKING_POLICY: 002140 (42601): SQL compilation error:
│ Unknown function SOME_UDF_MASK
│ 
│   with snowflake_masking_policy.masking_policy_1,
│   on main.tf line 27, in resource "snowflake_masking_policy" "masking_policy_1":
│   27: resource "snowflake_masking_policy" "masking_policy_1" {
│ 
╵
2022/03/03 09:10:30 [DEBUG] DELETE https://some-terraform-state-url/lock
Releasing state lock. This may take a few moments...
```

**Additional context**

After the above failure, I can log onto the Snowflake UI and see the UDF created on the database and schema. Using the same role used to create the UDF via terraform, I can run the SQL command `create or replace masking policy SOME_MASKING_POLICY as (val variant) returns variant -> SOME_UDF_MASK(val);` and create that masking policy specified in the terraform code without problem.

Furthermore, I tried creating the UDF in the Snowflake UI using the role that I use with terraform. I then tried to create the masking policy using terraform, and received the same error `Unknown function SOME_UDF_MASK`.

**Comment by thenaturalist** [comment]
Hi James, 
the error trace definitely hints to a grant issue, permissions are insufficient. 
In my experience - unfortunately - Snowflake UI resource management is not transferrable to Terraform 1:1 and hence is hardly helpful for debugging. It seems that from the Snowflake UI, grants are assigned recursively, but in Terraform this does not happen and each grant needs to be called explicitly.

It's best to consult the documentation here. Checking the [Masking Policy Parameter docs](https://docs.snowflake.com/en/sql-reference/sql/create-masking-policy.html#parameters), the `expression_on_arg_name` block explains required grants in the case of using UDFs.

Also see an explicit grant example here: https://docs.snowflake.com/en/sql-reference/sql/create-masking-policy.html
In the section `Using JavaScript UDFs on JSON (Variant)`, an explicit `OWNERSHIP` grant is added.

My guess is that once you add the appropriate grant explicitly, this should work in TF.

**Comment by internetofjames** [comment]
@thenaturalist thanks for the suggestion! I tried giving explicit ownership and usage permission to the role that my snowflake provider is configured with (the one that also creates the UDF). 

Unfortunately, I am still getting the same "unknown function" error in the masking policy.

**Comment by internetofjames** [comment]
**Update** -- I had the thought today on what the issue might be after reading (Naming Conventions for UDFs)[https://docs.snowflake.com/en/sql-reference/udf-overview.html#naming-conventions-for-udfs] in the Snowflake Docs, particularly, this excerpt:
> UDFs are database objects, meaning that they are created in a specified database and schema. As such, they have a fully-qualified name defined by their namespace, in the form of db.schema.function_name

In the example, my terraform code does not use the fully qualified names. Perhaps the provider is unable to resolve the context when applying changes? Or rather, it is not running within the context of a database and/or schema? Either way, adding the database and schema qualifiers in my terraform code has resolved this issue.

Subsequent `terraform apply` commands after initial creation, however, is a different story... for right now, `terraform destroy` followed by `terraform apply` seems to work around this issue.
