### ISSUE TITLE
Feature Request:  add "email" as property to `snowflake_user` resource

### ISSUE THREAD

**Issue by kylelundstedt** [chanzuckerberg/terraform-provider-snowflake#92]
Hi Team CZ

We've just adopted Snowflake, so I've just started using your cool TF provider.  Just a suggestion - can you add "email" as a property for the `snowflake_user` resource?

The reasoning is that, without associating an email with a new Snowflake user, it is impossible for that user to use the "Forgot Password" functionality.  Thanks!

**Comment by ryanking** [comment]
@kylelundstedt thanks for the interest.

Yeah we should support this, but we prioritize things our team uses (and this is not one of them), so I am not sure when we will get to it.

In the meantime, we would be happy to help get a PR merged.

**Comment by yuriolive** [comment]
@kylelundstedt Using Federated Authentication is a solution https://docs.snowflake.net/manuals/user-guide/admin-security-fed-auth-overview.html

So the user can reset their password using Azure AD for example. **login_name** must be the e-mail address associated to the Azure AD in this case.
