### ISSUE TITLE
Error: 5 or 6 fields allowed (using snowflake_role_grants)

### ISSUE THREAD

**Issue by alexsanderp** [chanzuckerberg/terraform-provider-snowflake#922]
**Provider Version**
0.28.6

**Terraform Version**
1.1.7

**Describe the bug**

Error: 5 or 6 fields allowed (using snowflake_role_grants)

**Expected behavior**

In version 0.27.0 it works normally

**Code samples and commands**

```
resource "snowflake_role_grants" "dadosfera" {
  role_name = snowflake_role.dadosfera.name

  users = [
    snowflake_user.dadosfera.name
  ]
}
```

**Additional context**

![image](https://user-images.githubusercontent.com/30603084/158252624-e46ee833-6526-4731-88a4-b61492afff88.png)

**Comment by jiangok-open** [comment]
FYI, 0.28.6 darwin amd64 flavor works fine on my MAC.

**Comment by alexsanderp** [comment]
Here it works on any release below 0.27.0

**Comment by jaeglee0416** [comment]
See comment: https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/923#issuecomment-1068420936

I wonder if the fix should have been `>= 1` on number of fields (for role grants to other roles).

https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs/resources/role_grants

There is only one "required" field `role_name`.
We're now running into issues with `4 to 6 fields allowed in ID`

**Comment by daniepett** [comment]
The original code prior to https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/824/files

Allowed a 4 or 5 length pipe delimited ID, because the grant privilege isn’t always included. It now allows 4,5 or 6 values. Can you include the ID from your statefile and I’ll investigate.

**Comment by nickperrott** [comment]
Does anybody know of a work-around for this issue while we wait for the next release?

**Comment by nickperrott** [comment]
Answered my own question setting replace_on_changes=["users"] in the ResourceOptions seems to be a good workaround.   I am using the provider via Pulumi though, but I guess Terraform has this option also.

**Comment by ChrisIsidora** [comment]
@nickperrott there is no option like that in terraform

**Comment by extdponomarchuk** [comment]
Got the same issue 
`│ Error: 4 to 6 fields allowed in ID
│ 
│   with snowflake_role_grants.role_grants["QA_SHAREADMIN"],
│   on grants.tf line 125, in resource "snowflake_role_grants" "role_grants":
│  125: resource "snowflake_role_grants" "role_grants" {`

So, rolled back to version "0.25.36"

**Comment by daniepett** [comment]
I’ll fix the role grants over the weekend

**Comment by ChrisIsidora** [comment]
I created a rollback of the changes @daniepett @alldoami
