### ISSUE TITLE
ALL privilege missing in `snowflake_schema_grant`

### ISSUE THREAD

**Issue by kylelundstedt** [chanzuckerberg/terraform-provider-snowflake#93]
Hi Team CZ,

I think there's still a schema privilege issue related to #68.  When I try to grant the "ALL" privilege using `snowflake_schema_grant`, I get the following error: 

```
Error: expected privilege to be one of [MODIFY MONITOR USAGE CREATE TABLE CREATE VIEW CREATE FILE FORMAT CREATE STAGE CREATE PIPE CREATE STREAM CREATE TASK CREATE SEQUENCE CREATE FUNCTION CREATE PROCEDURE], got ALL

  on roles.tf line 36, in resource "snowflake_schema_grant" "internal_schema_grant_bkfs_raw":
  36: resource "snowflake_schema_grant" "internal_schema_grant_bkfs_raw" {
```

Shouldn't "ALL" be a valid option?
https://docs.snowflake.net/manuals/user-guide/security-access-control-privileges.html#schema-privileges

Thanks!

**Comment by kylelundstedt** [comment]
Your docs also appear to suggest that "OWNERSHIP" is a valid privilege for `snowflake_schema_grant`.  Am I reading that wrong?

**Comment by thalesmello** [comment]
Usually "ALL" is a shortcut for granting all the other privileges at the same time. So I don't think it would make sense for them to exist as a terraform resource.

But an alternative to this could be a terraform module that creates all the grants at the same time.

**Comment by kylelundstedt** [comment]
Whoops!  I just realized that #81 added support for granting ownership for schemas, but it isn't in the current release (v0.4.1).  Moreover, reading the code alerted me to the fact that you all "Intentionally exclude the "ALL" alias because it is not a real privilege".  My apologies for not noticing these things earlier.
