### ISSUE TITLE
Feature request: Add support for network policy

### ISSUE THREAD

**Issue by andehen** [chanzuckerberg/terraform-provider-snowflake#94]
Hi! This provider works really well for us, nice work! :raised_hands: 

Any plans to add support for "network policy"? (Ref. https://docs.snowflake.net/manuals/sql-reference/sql/create-network-policy.html)

Cheers,
Anders

**Comment by ryanking** [comment]
Hey @andehen- 

We mostly build things our team(s) actually use and we don't currently use network policies. So there are no current plans to build support for it, but we would be happy to help get a PR merged.

**Comment by andehen** [comment]
Completely understandable!

I'll see if I can find time to submit a PR for this.

**Comment by ryanking** [comment]
Done in https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/271

**Comment by ryanking** [comment]
Done in https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/271
