### ISSUE TITLE
Provider docs haven't been updated with the new `host` arg

### ISSUE THREAD

**Issue by aidanmelen** [chanzuckerberg/terraform-provider-snowflake#959]
**Provider Version**

v0.30.0

**Describe the bug**

The provider docs haven't been updated with the new [`host`](https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs) argument

**Comment by yohei1126** [comment]
@aidanmelen Would you provide a PR?

**Comment by aidanmelen** [comment]
> @aidanmelen Would you provide a PR?

If it is an easy as running `make docs` then sure. @Dirrk did you forget to build the docs or is something broke with that workflow?

**Comment by Dirrk** [comment]
@aidanmelen I ran `make docs` and pushed up https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/939/commits/2b1d9eb06ae0bcc1a2017e03b75d8f6a43ee8a23

**Comment by aidanmelen** [comment]
> @aidanmelen I ran `make docs` and pushed up [2b1d9eb](https://github.com/chanzuckerberg/terraform-provider-snowflake/commit/2b1d9eb06ae0bcc1a2017e03b75d8f6a43ee8a23)

You definitely did. I also noticed that you added Description to the `provider.go` schema. That was a nice touch on your part.

**Comment by Dirrk** [comment]
I have another PR coming exposing the port and protocol options to the driver which we have tested locally for almost 2 weeks now.  I will make sure the docs get updated in that PR as well before submitting.

**Comment by aidanmelen** [comment]
@alldoami it looks like the `docs/index.md` file was generated correctly, but the terraform registry is showing the same docs as version `v0.29.0`

Link: https://undefined/providers/chanzuckerberg/snowflake/latest/docs
